### ISSUE TITLE
Arm64 Alpine docker image does not work with self-contained app

### ISSUE THREAD

**Issue by Flaminel** [dotnet/dotnet-docker#4186] opened 2022-11-04 16:03 UTC
### Describe the Bug

I am trying to build a docker image with a self-contained app based on the alpine versions of dotnet docker images, but the entrypoint is failing with the following message:
`/bin/sh: ./app: not found`

### Steps to Reproduce

I am using a Raspberry Pi 4 for this, with Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-1017-raspi aarch64).
Do these steps on an arm64 device:
```
dotnet new console --name app
cd app
nano Dockerfile
```
Content of Dockerfile:
```
FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine AS build
WORKDIR /app
EXPOSE 80

COPY . ./

RUN dotnet publish "./app.csproj" \
    -c Release \
    -o /app/publish \
    --use-current-runtime \
    --self-contained \
    /p:PublishSingleFile=true

FROM mcr.microsoft.com/dotnet/runtime-deps:7.0-alpine


WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ./app
```

```
sudo docker buildx build . --file Dockerfile --output type=image -t app:1
sudo docker run --rm -it app:1
```

### Other Information

I have also tried building the docker image on WSL and on a GitHub Runner using buildx + qemu for linux-arm64 and it has the same end result. Changing the dotnet version from 7 to 6 has the same result.
Using alpine images to run the app as framework-dependent works as expected.
Using jammy images to run the app as self-contained works as expected.

### Output of `docker version`

```
Client:
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.18.5
 Git commit:        100c70180f
 Built:             Tue Sep 20 06:36:20 2022
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.5
  Git commit:       a89b842
  Built:            Tue Sep 20 06:37:16 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Output of `docker info`

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.5.0)

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 18
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version:
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-1017-raspi
 Operating System: Ubuntu Core 18
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.7GiB
 Name: ubuntu
 ID: UUWX:PJX3:ZZIB:JB6K:GRZC:RSDU:V66O:QCXH:4GMC:32FR:P7K2:FGKR
 Docker Root Dir: /var/snap/docker/common/var-lib-docker
 Debug Mode: false
 Username: flaminel
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by mthalman** [comment] 2022-11-04 18:36
Pretty sure you're running into https://github.com/dotnet/sdk/issues/28809. Instead of using `--use-current-runtime` can you use `-r linux-musl-arm64` to verify that works?

**Comment by Flaminel** [comment] 2022-11-04 19:24
I cannot believe I didn't find that issue when I was searching for this problem.
You are right though. The problem goes away if I explicitly give it the correct runtime. I'll have to wait for a fix in the SDK since I'm trying to build multiarch images.

**Comment by mthalman** [comment] 2022-11-04 19:29
Your other option is to use an `ARG` that specifies the RID you want.

**Comment by mthalman** [comment] 2022-11-04 19:29
Duplicate of https://github.com/dotnet/sdk/issues/28809

**Closed by mthalman** 2022-11-04 19:29 UTC
Labels: bug, untriaged

**Comment by deuriib** [comment] 2023-04-09 21:36
> Pretty sure you're running into [dotnet/sdk#28809](https://github.com/dotnet/sdk/issues/28809). Instead of using `--use-current-runtime` can you use `-r linux-musl-arm64` to verify that works?

this works for me 🤓
