### ISSUE TITLE
“[/usr/share/dotnet/host/fxr] does not contain any version-numbered child folders“ when build for linux/arm/v7 platform

### ISSUE THREAD

**Issue by vincent-scw** [dotnet/dotnet-docker#3760] opened 2022-05-10 09:09 UTC
### Describe the Bug

I get “[/usr/share/dotnet/host/fxr] does not contain any version-numbered child folders“ error when use buildx to build for linux/arm/v7 platform.

### Steps to Reproduce
I am running build with buildx like ```docker buildx build ./src --platform linux/arm/v7 --file ./src/Sample/Dockerfile --tag xxx/sample:latest```

The Dockerfile I am using looks like
```
FROM mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim-arm32v7 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /src
COPY . .
RUN dotnet restore "Sample/Sample.csproj"
WORKDIR "/src/Sample"
RUN dotnet build "Sample.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Sample.csproj" -c Release -o /app/publish

FROM base AS final

WORKDIR /app
COPY --from=publish /app/publish .
ENV CONFIG_PATH=/var/Sample/config.json
ENTRYPOINT ["dotnet", "Sample.dll"]
```
Then I get ```A fatal error occurred, the folder [/usr/share/dotnet/host/fxr] does not contain any version-numbered child folders``` error at step "RUN dotnet restore "Sample/Sample.csproj"

### Other Information

I am running it in my Windows 10 64bit environment. I also tried to use ```FROM mcr.microsoft.com/dotnet/sdk:6.0-bullseye-slim AS build``` and ```FROM mcr.microsoft.com/dotnet/sdk:6.0-bullseye-slim-arm32v7 AS build``` for sdk image. But the error is the same.

The output for ```docker buildx ls```:
```
desktop-linux   docker
  desktop-linux desktop-linux   running linux/amd64, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6
default *       docker
  default       default         running linux/amd64, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6
```

### Output of `docker version`

Client:
 Cloud integration: v1.0.22
 Version:           20.10.13
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 10 14:13:04 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.6.0 (75818)
 Engine:
  Version:          20.10.13
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       906f57f
  Built:            Thu Mar 10 14:06:05 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.10
  GitCommit:        2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### Output of `docker info`

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.0)
  compose: Docker Compose (Docker Inc., v2.3.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 20.10.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.36GiB
 Name: docker-desktop
 ID: 32IV:22YJ:ZC75:TIMO:YJGS:SHKR:4EBV:2ZWW:MHNL:2TIS:B5S6:WT6A
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support

**Comment by mthalman** [comment] 2022-05-10 12:51
Duplicate of https://github.com/dotnet/dotnet-docker/issues/1291

**Closed by mthalman** 2022-05-10 12:51 UTC
Labels: bug, area-infrastructure, untriaged

**Comment by jelalanne** [comment] 2022-08-26 14:11
> Duplicate of #1291

Come on man, this answer is 3 years old, there should be a better option!
