### ISSUE TITLE
Non-admin user does not have enough permission on mounted volumes

### ISSUE THREAD

**Issue by dealdiane** [dotnet/dotnet-docker#569] opened 2018-06-05 23:35 UTC
## Steps to reproduce the issue
1. Create a "root" folder in C:\ with a "src" sub-directory and add dummy files in it.
2. Run docker run --rm -v "C:\root\src:c:\app" microsoft/dotnet:2.1-sdk cmd /c dir c:\app\src

## Expected behavior
Should list all files in C:\app\src

## Actual behavior
Getting an "Access is denied" error

## Additional information
The issue happens all the time every single time. 
If you run the container as the ContainerAdministrator, you won't get the error though.

## Output of `docker version`

```
Client:
 Version:       17.06.2-ee-10
 API version:   1.30
 Go version:    go1.8.7
 Git commit:    66261a0
 Built: Fri Apr 27 00:42:30 2018
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-10
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   66261a0
  Built:        Fri Apr 27 00:54:58 2018
  OS/Arch:      windows/amd64
  Experimental: false
```

## Output of `docker info`

```
Containers: 22
 Running: 0
 Paused: 0
 Stopped: 22
Images: 28
Server Version: 17.06.2-ee-10
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows Server Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 1.999GiB
Name: WIN-PIGSMFDG7FS
ID: IBZ4:JZOX:RAC7:WEYW:2KCM:VMVG:YFRH:NPJS:3TTK:LTM3:WKWL:TW6M
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by MichaelSimons** [comment] 2018-06-06 14:01
@dealdiane - This is the expected behavior of Windows Containers.  You can read about the permissions model for Bind Mounts [here](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-storage#permissions).  

I'm closing this issue since it is not specific to the microsoft/dotnet images.  Feel free to continue the conversation.  Any questions specific to Windows Containers should be posted to the [Windows Containers Forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers).

**Closed by MichaelSimons** 2018-06-06 14:01 UTC

**Comment by dealdiane** [comment] 2018-06-07 10:07
Yep. That fixed it. Thanks.

Should that be included in the doc so that everyone whose not aware of it won't get stuck especially that ContainerUser is now the default?

**Comment by MichaelSimons** [comment] 2018-06-07 13:19
Two places I see where it would make sense to mention this is at https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/dotnet-docker-dev-in-container.md#run-your-application-in-a-container-while-you-develop and https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/aspnet-docker-dev-in-container.md#run-your-application-in-a-container-while-you-develop.  Feel free to make a PR as we welcome contributions 😺

**Comment by DKroot** [comment] 2022-07-08 14:25
@dealdiane Thank you! It solved the issue: `mkdir out && icacls out /grant "Authenticated Users":(OI)(CI)M` in an Admin Command Prompt. BTW, PowerShell complains: the command likely just needs some escaping.
