### ISSUE TITLE
Sample Dockerfiles should exist that demonstrate how to use the new Windows Server Core images

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#2424] opened 2020-12-01 13:54 UTC
With the [introduction of Windows Server Core based images in 5.0](https://github.com/dotnet/dotnet-docker/issues/2377), new `windowsservercore` Dockerfiles should be added to the samples that illustrate how to best use the images.

**Comment by mthalman** [comment] 2020-12-02 13:47
This is a duplicate of https://github.com/dotnet/dotnet-docker/issues/2275 which was mistakenly closed.  I'll re-open it.

**Closed by mthalman** 2020-12-02 13:47 UTC
Labels: area-samples, bug, untriaged
