### ISSUE TITLE
Missing Tags for Architectures

### ISSUE THREAD

**Issue by bkant240** [dotnet/dotnet-docker#3264] opened 2021-11-04 12:54 UTC
'3.1-focal', '3.1-bionic', '3.1-bullseye' tags are unavailable for linux arm64 and linux arm32. Accordingly, my docker build with base image mcr.microsoft.com/dotnet/sdk:3.1-focal succeeds when built on an amd64 platform and fails when built on arm64 with the following warning:

`The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

<img width="1120" alt="Screen Shot 2021-11-04 at 8 50 52 AM" src="https://user-images.githubusercontent.com/3260037/140316675-2c96121e-01af-4e9b-b243-cfa2c3900ca3.png">

**Comment by mthalman** [comment] 2021-11-10 19:07
Triage: This is by design. For .NET Core 3.1, there are no multi-arg tags on a per-distro basis. The tags you listed are all amd64-based as [documented](https://github.com/dotnet/dotnet-docker/blob/main/documentation/supported-tags.md):

> For .NET Core 3.1, amd64 is the implied default if no architecture is specified.

Starting with the .NET 5 release, there are now multi-arch tags for each Linux distro. This was not retroactively done for .NET Core 3.1 because it would have been a breaking change.

To handle this for .NET Core 3.1, you'll need to explicitly provide the architecture in the tag name.

Closing as by design.

**Closed by mthalman** 2021-11-10 19:07 UTC
Labels: area-dockerfiles, untriaged
