### ISSUE TITLE
ExecutionPolicy breaking change in 6.0.423

### ISSUE THREAD

**Issue by perosb** [dotnet/dotnet-docker#5558] opened 2024-06-12 08:54 UTC
### Describe the Bug

A breaking change was discovered when trying to run our images using the .423 version of sdk:6.0
It seem the ExecutionPolicy has changed between 422 and 423.
Possible comes with the change of pwsh v7.2.20?

```
Status: Downloaded newer image for mcr.microsoft.com/dotnet/sdk:6.0.423
PowerShell 7.2.20

PS C:\> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine       Undefined
```

### Other Information

```
Status: Downloaded newer image for mcr.microsoft.com/dotnet/sdk:6.0.422
PowerShell 7.2.19

PS C:\> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine    RemoteSigned
```

Looking at latest 8.0:
```
Status: Downloaded newer image for mcr.microsoft.com/dotnet/sdk:8.0.302-nanoserver-ltsc2022
PowerShell 7.4.2
PS C:\> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine    RemoteSigned
```

Latest 6.0-alpine:
```
11:17 $ docker run -ti --entrypoint pwsh mcr.microsoft.com/dotnet/sdk:6.0-alpine
PowerShell 7.2.20

PS /> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy    Unrestricted
   UserPolicy    Unrestricted
      Process    Unrestricted
  CurrentUser    Unrestricted
 LocalMachine    Unrestricted
```

### Output of `docker info`

```
Client:
 Version:    26.1.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.3
    Path:     C:\Users\Administrator\.docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.3
    Path:     C:\Users\Administrator\.docker\cli-plugins\docker-compose.exe
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.17.1
    Path:     C:\Users\Administrator\.docker\cli-plugins\docker-scout.exe

Server:
 Containers: 32
  Running: 12
  Paused: 0
  Stopped: 20
 Images: 430
 Server Version: 25.0.4
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 20348 (20348.1.amd64fre.fe_release.210507-1500)
 Operating System: Microsoft Windows Server Version 21H2 (OS Build 20348.2031)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.86GiB
 Name: perosb-dev
 ID: 839d87f5-a9d7-4e93-8935-83f3db859824
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Username: osbeck
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by mthalman** [comment] 2024-06-12 13:37
@adityapatwardhan - Are you aware of this? Is there any documentation on it?

**Comment by adityapatwardhan** [comment] 2024-06-12 14:10
Let me have a look

**Comment by QuistZhang** [comment] 2024-06-12 18:16
![image](https://github.com/dotnet/dotnet-docker/assets/4004398/6d938734-47d7-44df-80a3-f700e6090fce)

I just diff-ed PowerShell.Windows.x64.7.2.19.nupkg and PowerShell.Windows.x64.7.2.20.nupkg  
7.2.20 package does not have tools\net6.0\any\powershell.config.json which was used to configure execution policy in 7.2.19 
`{
  "Microsoft.PowerShell:ExecutionPolicy": "RemoteSigned",
  "WindowsPowerShellCompatibilityModuleDenyList": [
    "PSScheduledJob",
    "BestPractices",
    "UpdateServices"
  ]
}`

**Comment by lbussell** [comment] 2024-06-13 18:29
@adityapatwardhan can you provide a workaround for this?

**Comment by adityapatwardhan** [comment] 2024-06-13 18:32
There is a workaround script for the issue. We will be fixing this issue in the next release.

After starting the container please run the script: https://gist.github.com/adityapatwardhan/f8c3435cfff6ae14fb0125e1b87b52b7

Use the following command to run the linked script:

```
pwsh -ExecutionPolicy bypass -c C:\temp\set-powershellconfig.ps1
```

**Comment by asos-gaborbuzasi** [comment] 2024-06-17 13:37
It seems like that this issue is fixed already in later PowerShell versions (e.g. 7.4.2 as pointed out by @perosb).
Is there any reason not to just upgrade the PowerShell version for the .NET 6.0 SDK docker image?

**Comment by mthalman** [comment] 2024-06-17 13:58
> It seems like that this issue is fixed already in later PowerShell versions (e.g. 7.4.2 as pointed out by @perosb). Is there any reason not to just upgrade the PowerShell version for the .NET 6.0 SDK docker image?

That won't work. PowerShell 7.4.x is based on .NET 8.

**Comment by asos-gaborbuzasi** [comment] 2024-06-17 14:36
@adityapatwardhan what were the reasons for introducing this change in the latest .NET 6 supported Powershell version?

This is breaking all Azure DevOps pipelines using container jobs, where the container image is the .NET 6 SDK and it's running a pwsh task. Your proposed workaround doesn't work in this scenario either because any script that the pipeline would run gets extracted into a temporary script file:
> "C:\Program Files\powershell\pwsh.exe" -NoLogo -NoProfile -NonInteractive -Command ". 'C:\\__w\_temp\31933939-65e1-4fe9-b46b-c77eb7b87e93.ps1'"
.: File C:\\__w\_temp\31933939-65e1-4fe9-b46b-c77eb7b87e93.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.

So there's no way to set the execution policy before running a script - unless there's a way Microsoft could do that in their script runner [PowerShell task](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/PowerShellV2).

**Comment by adityapatwardhan** [comment] 2024-06-17 17:36
@asos-gaborbuzasi - The change was inadvertent. A release with fix is expected this week.

**Comment by MichaelSimons** [comment] 2024-06-18 18:28
@adityapatwardhan - Is the powershell team adding tests on their side to prevent future regressions like this?  Would it also make sense to add a test for this scenario in this repo?

**Comment by adityapatwardhan** [comment] 2024-06-18 18:34
Yes we plan to add tests specifically for this. I can submit a PR to add tests to this repo too.

**Comment by asos-gaborbuzasi** [comment] 2024-06-19 09:59
I can see that a new [release](https://github.com/PowerShell/PowerShell/releases/tag/v7.2.21) has been created per version 7.2.21, which has got the configuration file again.

However, it doesn't have an alpine image (and its signature) published. Is that intentional?

I'm trying to have this latest version merged into the .NET 6 SDK docker image (similarly to this PR https://github.com/dotnet/dotnet-docker/pull/5546) but it requires an alpine version too.

**Closed** 2024-06-19 17:41 UTC
Labels: bug, area-documentation

**Comment by mthalman** [comment] 2024-06-19 19:28
Images have been published with the fixed PowerShell version. See the announcement: https://github.com/dotnet/dotnet-docker/discussions/5580.
