### ISSUE TITLE
Running as Non Root User Yields realpath(): Permission denied messages

### ISSUE THREAD

**Issue by ronifferte** [dotnet/dotnet-docker#1104] opened 2019-05-03 16:08 UTC
## Steps to reproduce the issue
1. Create a simple .net core console app (i.e. Hello World) using .net core 2.2
2. Host the app in docker container. Utilize the default Dockerfile created by Visual Studio 2019.
3. Update the docker file to specify a non root user
4. When run, realpath(): Permission denied error messages appear

## Expected behavior
My expectation is that the container would run without any error messages.

## Actual behavior
The container appears to output non-application specific (potentially runtime) error messages.

## Additional information (e.g. issue happens only occasionally)
This was tested using Docker Enterprise edition while running within Kubernetes.

## Output of `docker version`

```
Client:
 Version:           18.09.4
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        c3516c43ef
 Built:             Wed Mar 27 18:11:13 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Enterprise 2.1
 Engine:
  Version:          18.09.4
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       c3516c4
  Built:            Wed Mar 27 18:05:47 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 Universal Control Plane:
  Version:          3.1.3
  ApiVersion:       1.39
  Arch:             amd64
  BuildTime:        Mon Jan 28 18:25:34 UTC 2019
  GitCommit:        4be4a1f
  GoVersion:        go1.10.6
  MinApiVersion:    1.20
  Os:               linux
 Kubernetes:
  Version:          1.11+
  buildDate:        2019-01-15T17:33:26Z
  compiler:         gc
  gitCommit:        3e62468863641262df4dfd2a66610d23d4d792dd
  gitTreeState:     clean
  gitVersion:       v1.11.5-docker-4
  goVersion:        go1.10.6
  major:            1
  minor:            11+
  platform:         linux/amd64
 Calico:
  Version:          v3.5.0
  cni:              v3.5.0
  kube-controllers: v3.5.0
  node:             v3.5.0

```
Dockerfile:
[Dockerfile.txt](https://github.com/dotnet/dotnet-docker/files/3142662/Dockerfile.txt)

Output - Running As Root
![Container Log When Running As Root](https://user-images.githubusercontent.com/33876277/57150147-7f9f1000-6d9b-11e9-8ce9-3de02e17ff4c.png)

Output - Running As Non Root
![Container Log When Running As Non-Root](https://user-images.githubusercontent.com/33876277/57150146-7f067980-6d9b-11e9-9ed1-35e401b3e541.png)

**Comment by ronifferte** [comment] 2019-05-03 16:11
Dockerfile was cut off - apologies.

[Dockerfile.txt](https://github.com/dotnet/dotnet-docker/files/3142702/Dockerfile.txt)

**Comment by mthalman** [comment] 2019-05-10 17:15
Duplicate of https://github.com/dotnet/core-setup/issues/4038.  Please follow up on that issue if necessary.

**Closed by mthalman** 2019-05-10 17:15 UTC
