### ISSUE TITLE
Images for .NET Core on Windows Server Core

### ISSUE THREAD

**Issue by mattleibow** [dotnet/dotnet-docker#741] opened 2018-10-11 12:16 UTC
Not sure of the reason they don't exist, but I am sure someone will post a comment soon 😺 

Anyway, this is very useful so I don't have to download an install the Core SDK each time on my images.

A practical use case is this issue: https://github.com/mono/SkiaSharp/issues/591. As a result, I had to create a longer Dockerfile to first create a container, install .NET Core SDK, and then build my app, create a new container, install the Core Runtime and then run my app: https://gist.github.com/mattleibow/32ff6d124e7b5b93e94f1eb45d243aba

I don't mind installing the vc_redist at this point, as I only have to do it on the runtime container, and I hope to be removing this step, but I hope to be able to just pull the latest .NET Core image that can do things that need more Win32 features.

**Comment by mattleibow** [comment] 2018-10-11 12:16
I created a broken PR #732 that I need to fix if this is something that will ever be accepted.

**Comment by MichaelSimons** [comment] 2018-10-11 13:52
This is a duplicate of https://github.com/dotnet/dotnet-docker/issues/332.

The reason only Windows Nano Server images exist for .NET Core is because it is the best Windows Server container environment to run your .NET Core apps on. It is a much smaller SKU - smaller attack surface area, better performance, etc. .NET Framework has a Windows Server Core image because it is the only Windows Server container environment it is supported on.

The current recommendation for scenarios like yours would be to create your own Windows Server Core image which included .NET Core. You could start with the current .NET Core Nano Server Dockerfiles and change the FROM.

**Closed** 2018-10-11 17:47 UTC

**Comment by mattleibow** [comment] 2018-10-11 17:58
Makes sense. Not too much extra work.
