### ISSUE TITLE
Image.FromStream throws ArgumentException in Alpine based docker image when trying to load gif

### ISSUE THREAD

**Issue by skadenic19** [dotnet/dotnet-docker#1541] opened 2019-12-30 07:21 UTC
## Steps to reproduce the issue
1. Create asp net core project. 
2. Use command System.Drawing.Image.FromStream("/app/Images/1.gif")
3. Use base image mcr.microsoft.com/dotnet/core/aspnet:2.2-alpine
4. Use additional libs:

apk add libgdiplus --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted
apk add --no-cache libgcc icu-dev libc6-compat icu-libs giflib

4. Use microsoft/dotnet:2.2-sdk to build project

## Expected behavior

Image is loading correctly without exception

## Actual behavior

System.ArgumentException: Parameter is not valid.
   at System.Drawing.Image.InitializeFromStream(Stream stream)
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
   at TestGdiDotnet2.TryLoadImages.DoProduce(Object state) in /src/TestGdiDotnet2/TryLoadImages.cs:line 55

## Additional information (e.g. issue happens only occasionally)

The problem is in Alpine based image only. When I use microsoft/dotnet:2.2-aspnetcore-runtime the same file is loaded correctly.

## Output of `docker version`

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

## Output of `docker info`

```
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 562
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 8.003GiB
Name: linuxkit-00155d8071b9
ID: M5ML:GEYK:HHTS:P3B4:YWOP:3MQT:Y6YC:CA73:BAQG:DCHE:2YD2:GEOG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 28
 Goroutines: 51
 System Time: 2019-12-30T07:11:05.1515601Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 nexus2.zyfra.com:8082
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by mthalman** [comment] 2019-12-30 15:25
Duplicate of https://github.com/dotnet/dotnet-docker/issues/1465

**Closed by mthalman** 2019-12-30 15:25 UTC
