### ISSUE TITLE
Not killing process on CTRL-C shutdown

### ISSUE THREAD

**Issue by PRIMETSS** [dotnet/dotnet-docker#219] opened 2017-03-13 01:30 UTC
## Steps to reproduce the issue
1. docker microsoft/dotnet latest image
2.Build Web app, dotnet new mvc, dotnet restore, dotnet build
3.Run app dotnet run
4. Now listening on: http://*:5000 Application started. Press Ctrl+C to shut down.
5. Browse to app (displays web site)
6. Hit CTRL-C
7. root@30ff962dac9b:/usr/mvc# Application is shutting down...
9. Edit Program.cs with nano editor, (insert space, delete space, save file)
8. Try to rebuild or run and get error
root@30ff962dac9b:/usr/mvc# dotnet run
/usr/share/dotnet/sdk/1.0.1/Microsoft.Common.CurrentVersion.targets(3987,5): warning MSB3026: Could not copy "obj/Debug/netcoreapp1.1/mvc.dll" to "bin/Debug/netcoreapp1.1/mvc.dll". Beginning retry 1 in 1000ms. The process cannot access the file '/usr/mvc/bin/Debug/netcoreapp1.1/mvc.dll' because it is being used by another process. [/usr/mvc/mvc.csproj]
9. list processes running 'ps'
See multiple PID with dotnet
  PID TTY          TIME CMD
     1 ?        00:00:00 bash
  1040 ?        00:00:00 dotnet
  1117 ?        00:00:00 dotnet
  1173 ?        00:00:00 dotnet
10. kill each PID 'kill -9 1040' 1117/1173 etc
11. dotnet build now runs OK no errors

## Expected behavior
Is this because dotnet is not cleanly shutting down?

## Output of `docker version`

```
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

## Output of `docker info`

```
Containers: 17
 Running: 1
 Paused: 0
 Stopped: 16
Images: 1
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: TWSI:WQDI:BQNO:S3RL:JJA3:PGPL:5F4W:RFTG:4BOR:USRK:PJSB:AJ2S
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 21
 Goroutines: 36
 System Time: 2017-03-13T01:28:58.2390481Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by MichaelSimons** [comment] 2017-03-14 16:05
@PRIMETSS, Thanks for logging this issue.  As a workaround I noticed if you run using the host (e.g. `dotnet bin\Debug\netcoreapp\myApp.dll`) the issue will not reproduce.  

Closing since this is an ASP.NET Core issue being tracked with https://github.com/aspnet/Hosting/issues/960.

**Closed by MichaelSimons** 2017-03-14 16:05 UTC
