### ISSUE TITLE
Focal ARM32 builds are failing due to libc6 package installation

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-docker#1747] opened 2020-03-16 16:39 UTC
## Steps to reproduce the issue
On a Linux ARM machine, run:
```
cd 5.0/runtime/focal/arm32v7
docker build .
```

This could be related to https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1867431

## Expected behavior
Docker build succeeds.

## Actual behavior
`Cannot utime: Operation not permitted` errors occur while installing libc6 package.

```
Step 1/3 : FROM arm32v7/ubuntu:focal
 ---> 6279a48140d8
Step 2/3 : RUN apt-get update     && apt-get install -y --no-install-recommends         libc6         libgcc1         libgssapi-krb5-2         libicu65         libssl1.1         libstdc++6         zlib1g     && rm -rf /var/lib/apt/lists/*
 ---> Running in bfe8f38ba4b1
Get:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease [255 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [79.7 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease [79.7 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease [79.7 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports focal/main armhf Packages [1239 kB]
Get:6 http://ports.ubuntu.com/ubuntu-ports focal/multiverse armhf Packages [142 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports focal/restricted armhf Packages [10.8 kB]
Get:8 http://ports.ubuntu.com/ubuntu-ports focal/universe armhf Packages [11.0 MB]
Fetched 12.9 MB in 5s (2467 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  gcc-10-base libc-bin libcrypt1 libgcc-s1 libk5crypto3 libkeyutils1 libkrb5-3
  libkrb5support0
Suggested packages:
  manpages glibc-doc locales krb5-doc krb5-user
Recommended packages:
  krb5-locales
The following NEW packages will be installed:
  gcc-10-base libcrypt1 libgcc-s1 libgssapi-krb5-2 libicu65 libk5crypto3
  libkeyutils1 libkrb5-3 libkrb5support0 libssl1.1
The following packages will be upgraded:
  libc-bin libc6 libgcc1 libstdc++6 zlib1g
5 upgraded, 10 newly installed, 0 to remove and 52 not upgraded.
Need to get 13.1 MB of archives.
After this operation, 36.2 MB of additional disk space will be used.
Get:1 http://ports.ubuntu.com/ubuntu-ports focal/main armhf gcc-10-base armhf 10-20200307-0ubuntu1 [18.7 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libgcc-s1 armhf 10-20200307-0ubuntu1 [36.2 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libcrypt1 armhf 1:4.4.10-10ubuntu4 [93.5 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libc6 armhf 2.31-0ubuntu6 [2133 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libc-bin armhf 2.31-0ubuntu6 [489 kB]
Get:6 http://ports.ubuntu.com/ubuntu-ports focal/universe armhf libgcc1 armhf 1:10-20200307-0ubuntu1 [36.2 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports focal/main armhf zlib1g armhf 1:1.2.11.dfsg-2ubuntu1 [48.7 kB]
Get:8 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libstdc++6 armhf 10-20200307-0ubuntu1 [441 kB]
Get:9 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libssl1.1 armhf 1.1.1d-2ubuntu6 [1081 kB]
Get:10 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libkrb5support0 armhf 1.17-6ubuntu4 [28.0 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libk5crypto3 armhf 1.17-6ubuntu4 [79.4 kB]
Get:12 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libkeyutils1 armhf 1.6-6ubuntu1 [9172 B]
Get:13 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libkrb5-3 armhf 1.17-6ubuntu4 [287 kB]
Get:14 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libgssapi-krb5-2 armhf 1.17-6ubuntu4 [101 kB]
Get:15 http://ports.ubuntu.com/ubuntu-ports focal/main armhf libicu65 armhf 65.1-1ubuntu2 [8209 kB]
[91mdebconf: delaying package configuration, since apt-utils is not installed
[0mFetched 13.1 MB in 4s (3388 kB/s)
Selecting previously unselected package gcc-10-base:armhf.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 4126 files and directories currently installed.)
Preparing to unpack .../gcc-10-base_10-20200307-0ubuntu1_armhf.deb ...
Unpacking gcc-10-base:armhf (10-20200307-0ubuntu1) ...
Setting up gcc-10-base:armhf (10-20200307-0ubuntu1) ...
Selecting previously unselected package libgcc-s1:armhf.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 4132 files and directories currently installed.)
Preparing to unpack .../libgcc-s1_10-20200307-0ubuntu1_armhf.deb ...
Unpacking libgcc-s1:armhf (10-20200307-0ubuntu1) ...
Replacing files in old package libgcc1:armhf (1:9.2.1-21ubuntu1) ...
Setting up libgcc-s1:armhf (10-20200307-0ubuntu1) ...
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 4134 files and directories currently installed.)
Preparing to unpack .../libc6_2.31-0ubuntu6_armhf.deb ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/arm-linux-gnueabihf/perl5/5.30 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/arm-linux-gnueabihf/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Checking for services that may need to be restarted...
Checking init scripts...
Checking for services that may need to be restarted...
Checking init scripts...
Nothing to restart.
Unpacking libc6:armhf (2.31-0ubuntu6) over (2.30-0ubuntu3) ...
tar: ./control: Cannot utime: Operation not permitted
tar: ./md5sums: Cannot utime: Operation not permitted
tar: ./shlibs: Cannot utime: Operation not permitted
tar: ./symbols: Cannot utime: Operation not permitted
tar: ./triggers: Cannot utime: Operation not permitted
tar: .: Cannot utime: Operation not permitted
tar: Exiting with failure status due to previous errors
dpkg-deb: error: tar subprocess returned error exit status 2
dpkg: error processing archive /var/cache/apt/archives/libcrypt1_1%3a4.4.10-10ubuntu4_armhf.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /var/cache/apt/archives/libcrypt1_1%3a4.4.10-10ubuntu4_armhf.deb
[91mE: Sub-process /usr/bin/dpkg returned an error code (1)
```

## Output of `docker version`

```
(paste your output here)
```

## Output of `docker info`

```
(paste your output here)
```

**Comment by mthalman** [comment] 2020-03-16 19:54
It's not clear whether https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1867431 is related.  So I've logged https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1867675 for this issue.

**Comment by thaJeztah** [comment] 2020-03-24 17:26
We ran into the same issue in the containerd packaging scripts (https://github.com/docker/containerd-packaging/pull/151), and it looks like the `Cannot utime: Operation not permitted` is caused by seccomp blocking something.

Now the question is if the default seccomp profile is blocking something that does not have to be blocked, or if something changed in the package (?) that's making syscalls it should not make

**Comment by mthalman** [comment] 2020-03-24 17:40
@thaJeztah - Feel free to respond to https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1867675  with anymore info.

**Comment by DeeDeeG** [comment] 2020-03-24 19:17
I already posted this in the `docker/containerd-packaging` issue, but posting here as well:

---

Not sure if this is helpful, but there is something here that sounds related. From the [changelog](http://changelogs.ubuntu.com/changelogs/pool/main/g/glibc/glibc_2.31-0ubuntu6/changelog) for [`libc6` in Focal](https://packages.ubuntu.com/focal/libc6):

> glibc (2.31-0ubuntu1) focal; urgency=medium
> 
>   * [...]
>   * Backport 5828bc4523230685ac29a4a882967913255f5666, making the clone3
>     syscall known on arm64, fixing misc/tst-glibcsyscalls.
>   * [...]
> 
>  -- Matthias Klose <doko [at] ubuntu.com>  Fri, 06 Mar 2020 12:06:42 +0100

Is this `clone3` perhaps the syscall that seccomp is getting tripped up on?

**Comment by mthalman** [comment] 2020-06-11 15:48
Apparently this is the issue being worked on to fix this: https://bugs.launchpad.net/ubuntu/+source/libseccomp/+bug/1877633.  It's in the process of being tested and backported.

**Comment by mthalman** [comment] 2020-07-09 21:36
I've tested this fix on an updated version of our build agent that is running Focal and it can now build the Dockerfile successfully.  Previously the build agent was running Xenial and was still encountering the same issue even with the "fixed" libseccomp2 package installed.  But after upgrading, things now work.  The next step is to roll out the upgrades of the build agents to use Focal.

**Comment by MichaelSimons** [comment] 2020-07-21 19:40
When hooking up the currently disabled Focal ARM Dockerfiles back into the build.  Please ensure the `dockerfileTemplate` property is defined in the manifest.json.  The current Focal ARM Dockerfiles checked into the repo are out of date and will need to be regenerated.

**Closed** 2020-08-11 20:42 UTC
Labels: area:dockerfiles, bug, triaged
