### ISSUE TITLE
Publish Multi-Runtime Images for SDK

### ISSUE THREAD

**Issue by Blackclaws** [dotnet/dotnet-docker#4160] opened 2022-10-24 08:01 UTC
### Describe the Problem

Especially in the current phase of transition between 6.0 and 7.0 (or possibly even longer as 7.0 is not an LTS release) there are a number of third party libraries that still ship with tools that are based on 6.0 and therefore require a 6.0 runtime to be installed.

Currently some of our builds are breaking in images where we don't manually install the 6.0 runtime. While its not that big of a hassle to manually create multi-runtime SDK builds it would be nice if there was some tag that combined runtimes.

### Describe the Solution

Introduce a new sdk tag either as a version suffix to the sdk (flavor) as a general new top level tag. Proposals:

dotnet/sdk-multi:7.0 (rolls up all runtimes until 7.0)

alternatively

dotnet/sdk:7.0-multi

I think creating _all_ different types of flavor is a bit too much, however combining the latest LTS release with the current release would make sense.

**Comment by mthalman** [comment] 2022-10-24 13:45
Duplicate of https://github.com/dotnet/dotnet-docker/issues/2048

**Comment by mthalman** [comment] 2022-10-26 18:07
Closing this based on it being a duplicate as previously stated.

**Closed by mthalman** 2022-10-26 18:07 UTC
Labels: enhancement, untriaged
