### ISSUE TITLE
microsoft/dotnet:1.0-sdk contains the 1.1.0 sdk

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/dotnet-docker#291] opened 2017-09-11 18:37 UTC
_From @brentarias on September 6, 2017 19:30_

The [Dockerhub image for aspnetcore-build](https://hub.docker.com/r/microsoft/aspnetcore-build/) does not contain the ASP.NET Core 1.0 image that it claims to contain.  The "tags" page indicates that "1.0" is allegedly one of the tags, but it isn't available.

## Steps to reproduce the issue
(e.g. copy your Dockerfile or docker-compose.yml file here)
1.  On Windows 10 Professional, invoke "docker pull microsoft/aspnetcore-build:1.0"
2.  Then run "docker container run -it microsoft/aspnetcore-build:1.0 powershell"
3.  In the container's terminal window, type "dotnet --version" or "dotnet --info"

## Expected behavior
"dotnet --version" should output "1.0", or at least a "1.0.x" version.

## Actual behavior
"dotnet --version" outputs "1.1.0"

## Additional information (e.g. issue happens only occasionally)
I have Docker configured for Windows containers.  Allegedly the docker hub image has a aspnet.core 1.0 image, as represented in the following dockerfile:
`https://github.com/aspnet/aspnet-docker/blob/master/1.0/nanoserver/sdk/Dockerfile`

## Output of `dotnet --info`
When executed directly on my laptop (not within a continer), then 'dotnet --info" outputs:
```
$ dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

## Output of `docker info`

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 1
Server Version: 17.06.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 7.916GiB
Name: DESKTOP-057K4L5
ID: VRHC:PY7B:3WNS:FDPL:PHX7:4LQ5:GVMZ:JIE7:K6GJ:VWAC:GYYZ:ZCV4
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 20
 System Time: 2017-09-06T12:25:34.9849615-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false```


_Copied from original issue: aspnet/aspnet-docker#291_

**Comment by natemcmaster** [comment] 2017-09-11 18:37
The `microsoft/aspnetcore-build` image gets its SDK from `microsoft/dotnet`. 

https://github.com/aspnet/aspnet-docker/blob/03260d72778f0127e954110e422fccfab081d04c/1.0/nanoserver/sdk/Dockerfile#L2

I'm moving this issue to the repo for this image so they can comment on or resolve this discrepancy.

https://github.com/dotnet/dotnet-docker/blob/9a4902275098fa1bfa659cd57f65470c30cf6a6b/1.0/sdk/nanoserver/Dockerfile#L5-L7

**Comment by MichaelSimons** [comment] 2017-09-11 19:32
@brentarias - The 1.0-sdk tag should be thought of as the image that contains the SDK you'd use to develop an app that targets the 1.0 runtime.  As noted, 1.1.0 is the SDK version you'd use to accomplish that.  The history behind this is rather long and complicated but stems from the 1.0 runtime RTM'ing before the SDK.  Starting with 1.1.3 and newer, there will be alignment with the runtime and sdk versioning to avoid this confusion.

Outside of the versioning mismatch - is there an issue with using the 1.1.0 SDK?

**Comment by brentarias** [comment] 2017-09-12 21:38
I don't understand.  Evidently, [there is no such thing as a 1.1.0 SDK](https://github.com/dotnet/core/blob/master/release-notes/download-archive.md).  The 1.x.x series of SDK ends at 1.0.4 and skips straight to 2.0.x.

It there any command I could type into the interactive docker container to prove that the runtime is actually 1.0.x instead of 1.1.x?

**Comment by MichaelSimons** [comment] 2017-09-12 22:44
1.1.0 is a release documented on CLI repo - https://github.com/dotnet/cli/tags.  @leecow - should the [.NET Core download archive](https://github.com/dotnet/core/blob/master/release-notes/download-archive.md) include the 1.1.0 SDK?

Regarding a command to list the installed runtimes - there isn't currently a dotnet command for this but one is coming soon.  See https://github.com/dotnet/core-setup/issues/675 for more details.  In the meantime you could run `ls /usr/share/dotnet/shared/Microsoft.NETCore.App/` on linux or `dir 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\'` on windows

**Comment by brentarias** [comment] 2017-09-13 04:35
Thank you for the dotnet/cli/tags link!  Also, I was aware of the dotnet\sdk folder for SDK's, but was unaware of the "dotnet\shared" folder for runtimes.  Thank you for that pointer!

Although we're waiting to hear from @leecow, I still perceive a problem.  When I use the `microsoft/aspnetcore-build:1.0` image, I expect an SDK that supports the old project.json build format.  IIRC, any SDK after `RC3 build 004530` requires csproj/msbuild.

I feel it partly defeats the purpose of a 1.0 runtime docker image...if the bundled SDK is 1.1.0.  Perhaps I need to look at this differently?  Perhaps Microsoft no longer officially supports the pre-RC4 SDK (project.json build) and thus the Docker image for aspnetcore-build does not offer it.  However, if that is true - then does that mean the [LTS release page](https://github.com/dotnet/core/blob/master/release-notes/download-archive.md) is incorrect?  

It would be very interesting if the aspnetcore-build docker image had an environment variable declared that allowed me to `docker run` with the SDK version I want.

In any case, now that I know how to investigate the `dotnet\shared` folder for runtimes, I now see that the image I pulled has:

 * 1.1.0 SDK
 * 1.0.5 runtime

I suppose this confirms a suspicion I had...that Microsoft no longer supports the 2016/06/27 "1.0" SDK, even though [it is listed under LTS](https://github.com/dotnet/core/blob/master/release-notes/download-archive.md).

Looks like 1.0.5 is the minimum supported run-time.  I'll adjust my upgrade path accordingly.

**Comment by leecow** [comment] 2017-09-13 16:39
Hi @brentarias - One of the requirements of LTS is that customers utilize the latest, released patch version. See https://www.microsoft.com/net/core/support for details. 

One thing we will be clarifying as we get ready to promote 2.0 to LTS is exactly what is covered under LTS. Tooling is one of the areas in a bit of limbo that we will make better.

**Comment by leecow** [comment] 2017-09-13 16:42
@MichaelSimons - as soon as we have a 'stand-alone' release which includes the 1.1 SDK, we'll add an entry to the download pages.

**Comment by brentarias** [comment] 2017-09-13 18:09
Hey @leecow!  I feel you've confirmed my understanding about the runtime (currently 1.0.5 is supported) but I'm not sure what this means for the SDK.  Although LTS details are still being worked out, would it be correct to say that all of the SDK's that use project.json are no longer supported?  Said differently, I suspect that SDK 1.0.4 is the earliest candidate LTS SDK.  Yes?

**Comment by leecow** [comment] 2017-09-14 01:01
@brentarias - Correct, SDKs of the project.json era are not supported. That's probably an OK way to think of 1.0.4 until we get things cleaned up.

**Comment by MichaelSimons** [comment] 2017-09-26 18:36
@brentarias - Are there anymore unanswered questions regarding this issue?  If not please feel free to close.

**Comment by MichaelSimons** [comment] 2017-10-03 20:57
Closing as it appears the questions were answered.  Feel free to create an issue if new questions arise.

**Closed by MichaelSimons** 2017-10-03 20:57 UTC
Labels: question, triaged
