### ISSUE TITLE
aspire-dashboard doesn't run by default

### ISSUE THREAD

**Issue by eerhardt** [dotnet/dotnet-docker#5258] opened 2024-03-12 19:26 UTC
### Describe the Bug

When trying to run the aspire-dashboard container, it fails by default.

### Steps to Reproduce

1. `docker pull mcr.microsoft.com/dotnet/nightly/aspire-dashboard`
2. `docker run --rm mcr.microsoft.com/dotnet/nightly/aspire-dashboard`

### Other Information

```
Unhandled exception. System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at Microsoft.AspNetCore.Builder.RequestLocalizationOptions.AddSupportedCultures(String[] cultures)
   at Aspire.Dashboard.DashboardWebApplication..ctor(Action`1 configureBuilder) in /_/src/Aspire.Dashboard/DashboardWebApplication.cs:line 125
   at Program.<Main>$(String[] args) in /_/src/Aspire.Dashboard/Program.cs:line 7
```

### Output of `docker version`

```
Client:
 Cloud integration: v1.0.35+desktop.11
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:02 2024
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.28.0 (139021)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:25 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Output of `docker info`

```
Client:
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.6-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.22
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.5.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 6
  Running: 5
  Paused: 0
  Stopped: 1
 Images: 37
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.146.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.27GiB
 Name: docker-desktop
 ID: b91f57ee-b93b-4ea5-a654-1524579c0558
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

@joperezr

**Comment by MichaelSimons** [comment] 2024-03-12 19:35
cc @lbussell, @joperezr - Looks like this was a regression introduced by https://github.com/dotnet/dotnet-docker/pull/5248.  Does this mean the images need to be loc enabled e.g. disable DOTNET_SYSTEM_GLOBALIZATION_INVARIANT?

**Comment by eerhardt** [comment] 2024-03-12 19:51
> Does this mean the images need to be loc enabled e.g. disable DOTNET_SYSTEM_GLOBALIZATION_INVARIANT?

Since this app is used to show UI to people, my assumption is it needs to be loc enabled.

cc @JamesNK @drewnoakes

**Comment by JamesNK** [comment] 2024-03-13 00:05
Is this the same as https://github.com/dotnet/aspire/issues/2764?

**Comment by MichaelSimons** [comment] 2024-03-13 13:39
> Is this the same as https://github.com/dotnet/aspire/issues/2764?

Yes it is.

> I don't know who maintains the Aspire dashboard docker container.

@lbussell and @joperezr

**Comment by lbussell** [comment] 2024-03-14 18:19
[Triage] Once https://github.com/dotnet/dotnet-docker/pull/5262 is merged I will submit a PR to add ICU and enable localization in the dashboard container.

**Comment by lbussell** [comment] 2024-03-19 21:14
Fixed in https://github.com/dotnet/dotnet-docker/pull/5276

**Closed by lbussell** 2024-03-19 21:14 UTC
Labels: bug, area-dockerfiles
