### ISSUE TITLE
dotnet/sdk@7.0.400 - Restore Nuget Package from Private Feeds

### ISSUE THREAD

**Issue by Nico-VanHaaster** [dotnet/dotnet-docker#4803] opened 2023-08-09 06:07 UTC
Using the latest release that targets 7.0.400 has issues restoring from private Nuget feeds. This was experienced both locally and using Azure DevOps pipelines.

This was first thought to be an issue with the feed itself however a standard `dotnet restore --no-cache` worked both locally and within DevOps pipelines.

Reverting the base image to dotnet/sdk@7.0.306 resolved the issues.

Error Captured:
```
error NU1301: Unable to load the service index for source https://nuget.hangfire.io/nuget/hangfire-pro/v3/index.json.
```

Running the dotnet restore command in diag mode did not produce (from what I can tell) meaningful results as to why it failed.

**Comment by mthalman** [comment] 2023-08-09 12:59
@nkolev92, @zivkan - Can you help out here to diagnose the issue? This occurred after updating the .NET SDK container images from 7.0.306 to 7.0.400.

**Comment by mthalman** [comment] 2023-08-09 17:51
@nkolev92 - I think the assumption here is that it's configured just fine since it worked in 7.0.306. We need to determine why it's not working in 7.0.400. What steps can be done by @Nico-VanHaaster to gather more diagnostic info to help determine the root cause?

**Comment by nkolev92** [comment] 2023-08-09 17:54
Depends how the authentication was being done previously. 
If it was being done through the config, then I'm not sure there's anything more than what diag shows.

If it was being done through a plugin, then https://github.com/NuGet/NuGet.Client/blob/dev/docs/plugin-logging.md has details about enabling logging and then that can tell you where things go wrong.

**Comment by Nico-VanHaaster** [comment] 2023-08-09 22:29
@mthalman 

Below is a sample docker file we use as a base SDK build image. 

We are using both Azure DevOps feeds (those ones work fine in the build) as well as a private Authenticated Nuget repository (Hanfire Pro)

<details>
<summary>Dockerfile Sample</summary>

```
ARG IMAGE_TAG=7.0
FROM mcr.microsoft.com/dotnet/sdk:${IMAGE_TAG} AS build
ARG ACCESS_TOKEN
ARG HANGFIRE_USER
ARG HANGFIRE_TOKEN
RUN curl -sL 'https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh' | bash
ENV VSS_NUGET_EXTERNAL_FEED_ENDPOINTS "{\"endpointCredentials\": [{\"endpoint\":\"https://api.nuget.org/v3/index.json\"}, {\"endpoint\":\"https://pkgs.dev.azure.com/companyname/_packaging/ParlPortal-CI/nuget/v3/index.json\", \"username\": \"PAT\", \"password\":\"${ACCESS_TOKEN}\"}, {\"endpoint\":\"https://nuget.hangfire.io/nuget/hangfire-pro/v3/index.json\", \"username\":\"${HANGFIRE_USER}\", \"password\":\"${HANGFIRE_TOKEN}\"}]}"
ENV DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
```
</details>


The code is pretty straight forward:
```
dotnet restore /path/toproject.csproj
```

Running a dotnet core restore command manually on our workstations and in the DevOps pipelines outside of Docker does not produce any issues.

However running these commands in the docker files (both locally and in Azure DevOps) produces the error 

```
error NU1301: Unable to load the service index for source https://nuget.hangfire.io/nuget/hangfire-pro/v3/index.json.
```

Now if I revert the tag from `ARG IMAGE_TAG=7.0` to `ARG IMAGE_TAG=7.0.306` then the docker images build correctly.

**Comment by Nico-VanHaaster** [comment] 2023-08-09 23:24
To add I have also tried using the alpine images (7.0.400) and the same issue happens.

**Comment by nkolev92** [comment] 2023-08-10 01:24
`VSS_NUGET_EXTERNAL_FEED_ENDPOINTS` in the docker file suggests you're using the plugin. 

Referring to https://github.com/dotnet/dotnet-docker/issues/4803#issuecomment-1671887995. 

You can try enabling plugin logging. It'll contain details about any NuGet <-> plugin interaction. 

Adding `/v:d` will also give more details about the whole operation.

**Comment by zivkan** [comment] 2023-08-14 07:38
I'd also like to know if getting the service index for `https://pkgs.dev.azure.com/companyname/_packaging/ParlPortal-CI/nuget/v3/index.json` was successful, or if it's only a problem with the `https://nuget.hangfire.io/nuget/hangfire-pro/v3/index.json` feed?

The NuGet team doesn't own the Azure Artifacts credential provider, and `hangfire.io` is not Azure Artifacts. So, while it's interesting that Azure Artifacts cred provider (sometimes?) works with 3rd party feeds, I don't know if it's a supported scenario (though I also don't understand why the same cred provider would change behaviour depending on .NET SDK version, the logs that Nikolche asked for would be very helpful). The NuGet team's supported feature is [using environment variables in nuget.config files](https://learn.microsoft.com/en-us/nuget/reference/nuget-config-file#using-environment-variables), for which [I created a sample](https://github.com/zivkan/nuget-config-environment-variable) years ago (though it looks like all the GitHub checks have disappeared, but the 3+ year old builds might not exist any longer either).

**Comment by Nico-VanHaaster** [comment] 2023-08-14 22:07
@mthalman @zivkan 

Sorry for the delay, I had taken a few days away from this issue. I do appreciate you following up. 

We have been using a similar docker file like above since dotnet core 3.1 days and using the Azure Artifacts credentials provider in the manor above. I have tested by swapping the hangfire nuget source to use environment variables for the username and the password (instead of the `VSS_NUGET_EXTERNAL_FEED_ENDPOINTS `) and this seems to work correctly. 

I am not sure why it would have stopped working in 7.0.400 vs the 7.0.306 version however I am happy to continue to use this approach.

<details>
<summary>Updated Docker File</summary>

```
RUN curl -sL 'https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh' | bash
ENV HANGFIRE_LOGIN=$HANGFIRE_USER
ENV HANGFIRE_PASSWORD=$HANGFIRE_TOKEN
ENV VSS_NUGET_EXTERNAL_FEED_ENDPOINTS "{\"endpointCredentials\": [{\"endpoint\":\"https://pkgs.dev.azure.com/company/_packaging/feed/nuget/v3/index.json\", \"username\": \"docker\", \"password\":\"${ACCESS_TOKEN}\"}]}"
ENV DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
```
</details>

<details>
<summary>Nuget.Config</summary>

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<configuration>
  <packageSources>
    <clear />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="Company-CI" value="https://pkgs.dev.azure.com/companyname/_packaging/feed/nuget/v3/index.json" protocolVersion="3" />
    <add key="HangfirePro" value="https://nuget.hangfire.io/nuget/hangfire-pro/v3/index.json" protocolVersion="3" />
  </packageSources>
  <packageSourceCredentials>
    <HangfirePro>
      <add key="Username" value="%HANGFIRE_LOGIN%" />
      <add key="ClearTextPassword" value="%HANGFIRE_PASSWORD%" />
    </HangfirePro>
  </packageSourceCredentials>
  <packageSourceMapping>
    <packageSource key="nuget.org">
      <package pattern="*" />
    </packageSource>
       <packageSource key="HangfirePro">
      <package pattern="Hangfire.Pro" />
      <package pattern="Hangfire.Pro.*" />
    </packageSource>
  </packageSourceMapping>
</configuration>
```
</details>

I guess that given the credentials provider is for Azure Artifacts only and not for external feeds then it makes sense that this issue should have shown up quite awhile ago. I have been through the release changes and tried previous versions of the Credential provider without success.

Thanks for looking into this, I am happy to close this issue unless you would like me to run some more diagnostics.

Cheers,
Nico

**Comment by mthalman** [comment] 2023-08-15 12:24
Thanks for following up @Nico-VanHaaster. I'll close this since it was an unsupported configuration.

**Closed by mthalman** 2023-08-15 12:24 UTC
Labels: bug, area-dockerfiles
