### ISSUE TITLE
Remove support for .NET 7.0 (EOL 	May 14, 2024)

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker#5420] opened 2024-05-02 15:26 UTC
Once .NET 7.0 reaches EOL, support for it should be removed.  Per the [Tag Lifecycle policy](https://github.com/dotnet/dotnet-docker/blob/main/documentation/supported-tags.md#tag-lifecycle).

_When a .NET version reaches EOL, its tags will continue to be maintained (rebuilt for base image updates) until the next .NET servicing date (typically on "Patch Tuesday", the 2nd Tuesday of the month)._

Therefore 7.0 support shouldn't be removed in main until June Patch Tuesday (6/11).  The work to remove the images from nightly can begin after May Patch Tuesday.

**Comment by lbussell** [comment] 2024-05-02 18:33
[Triage] Duplicate of https://github.com/dotnet/dotnet-docker/issues/5336

**Closed by lbussell** 2024-05-02 18:33 UTC
Labels: area-infrastructure, untriaged
