### ISSUE TITLE
dotnet restore from private TFS fails in docker build 

### ISSUE THREAD

**Issue by moisoiu** [dotnet/dotnet-docker#909] opened 2019-01-26 20:37 UTC
## Steps to reproduce the issue
1. Create a .dotnet application (Add docker support)
2. Add a nugget from your private TFS package manager
3. Create CI in TFS 
4. Add Docker Build 

## Expected behavior
Restore package from private TFS Package Manager successfully 

## Actual behavior
If dockerfile has _ENV DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0_
Returns:
`   /usr/share/dotnet/sdk/2.2.100/NuGet.targets(114,5): error : Unable to load the service index for source http://[redacted]/tfs/[redacted]/_packaging/CIS/nuget/v3/index.json. [/src/Web.csproj]
2019-01-26T20:07:00.2066187Z       `  
            
`   /usr/share/dotnet/sdk/2.2.100/NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized). [/src/Web.csproj]`

If I Remove  _ENV DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0_
`/usr/share/dotnet/sdk/2.2.100/NuGet.targets(114,5): error : Unable to load the service index for source http://[redacted]/tfs/[redacted]/_packaging/CIS/nuget/v3/index.json. [/src/Web.csproj]`

`/usr/share/dotnet/sdk/2.2.100/NuGet.targets(114,5): error :   GSSAPI operation failed with error - An invalid status code was supplied (Invalid value in argument). [/src/Web.csproj]`

## Additional information (e.g. issue happens only occasionally)
I've tried also to add `gss-ntlmssp` but it didn't fix the problem

## Output of `docker version`

```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:01 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:06:30 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

## Output of `docker info`

```
Containers: 81
 Running: 1
 Paused: 0
 Stopped: 80
Images: 2754
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.1.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.47GiB
Name: sdcclinuxagent1
ID: 7HUF:6K5U:N7PD:L6KL:VASU:R2VK:JGBF:LY2N:ARAZ:JKK2:I5G4:YHO4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by MichaelSimons** [comment] 2019-02-01 22:37
Closing issue - insufficient information to reproduce the issue (e.g. concrete repro steps, basic debug findings, etc). Feel free to reopen this issue with the additional information.

**Closed by MichaelSimons** 2019-02-01 22:37 UTC
Labels: needs more info

**Comment by Roll4D6** [comment] 2019-07-14 08:15
> Hi @MichaelSimons you're right, forgot to add the missing pieces. I've updated the flow.
> 
> It's weird that is working in TFS but not when doing in the dockerFile.
> 
> My workaround for now is that in private TFS I make the Restore / Build / Publish and after that copy them in the docker image.
> 
> Also another common error that throws is this ->
> `GSSAPI operation failed with error - An invalid status code was supplied (Configuration file does not specify default realm)`

any update on this issue? I'm currently suffering from the same error.
We have a private TFS server running on windows server and i try to get the nugets during the docker build and get the GSSAPI error. I've done some reading and it seems that the problem is that the  TFS server is running on windows kernel and using kerberos and the docker is using a linux kernel that cant use kerberos.

**Comment by moisoiu** [comment] 2019-07-15 09:21
Hello @Roll4D6  the "temp" solution would be here -> https://github.com/microsoft/artifacts-credprovider/issues/63

**Comment by eraigosa** [comment] 2020-07-23 17:15
I hope my solution here... https://github.com/microsoft/artifacts-credprovider/issues/63
