### ISSUE TITLE
Could not find file '/usr/share/zoneinfo/Europe/Kiev'.

### ISSUE THREAD

**Issue by TrayanZapryanov** [dotnet/dotnet-docker#6072] opened 2024-11-22 11:18 UTC
### Describe the bug

Once we migrated from jammy:8.0.10-amd64 to runtime:9.0.0-noble-chiseled-extra-amd64,
I can see following exception in our production logs:
**Could not find file '/usr/share/zoneinfo/Europe/Kiev'.**
![Image](https://github.com/user-attachments/assets/e83738c5-d962-4237-a533-1e220951caaf)
![Image](https://github.com/user-attachments/assets/0dfe2b8a-5c58-4976-ae8c-e6032dc59331)

Is there something wrong in our code?

### Which .NET image(s) are you using?

mcr.microsoft.com/dotnet/runtime:9.0.0-noble-chiseled-extra-amd64

### Steps to reproduce

TimeZoneInfo.FindSystemTimeZoneById("FLE Standard Time")

### Output of `docker version`

```console

```

### Output of `docker info`

```console

```

**Comment by mthalman** [comment] 2024-11-22 15:13
This is due to a difference in the `tzdata` package versions between Ubuntu 22.04 (jammy) and Ubuntu 24.04 (noble). 

In Ubuntu 22.04, the path `usr/share/zoneinfo/Europe/Kiev` was a symbolic link to the path `usr/share/zoneinfo/Europe/Kyiv`. In Ubuntu 24.04, that symbolic link was removed, leaving only the `usr/share/zoneinfo/Europe/Kyiv` path.

Pinging @dotnet/area-system-globalization for input on why `TimeZoneInfo` isn't accounting for this.

**Comment by richlander** [comment] 2024-11-22 16:09
Also see: https://discourse.ubuntu.com/t/ubuntu-24-04-lts-noble-numbat-release-notes/39890#p-99950-tzdata-package-split

**Comment by richlander** [comment] 2024-11-22 16:17
I am wondering if we should create breaking change issues, per OS version, and add to them over time. This is similar to the TLS 1.x change we saw earlier. We haven't come up with a good model on how to record these. Recording them in docs doesn't seem right to me. Docs should be dedicated to .NET product breaks. The goal is to make the full set of breaks discoverable.

@gewarren

**Comment by mthalman** [comment] 2024-11-22 16:48
> Also see: https://discourse.ubuntu.com/t/ubuntu-24-04-lts-noble-numbat-release-notes/39890#p-99950-tzdata-package-split

So this can be resolved by installing `tzdata-legacy`. I tried that and confirmed it does create the `usr/share/zoneinfo/Europe/Kiev` path.

But ideally, whatever code is looking for that path would be updated to use `usr/share/zoneinfo/Europe/Kyiv` instead.

**Comment by lbussell** [comment] 2024-11-22 16:51
> Also see: https://discourse.ubuntu.com/t/ubuntu-24-04-lts-noble-numbat-release-notes/39890#p-99950-tzdata-package-split

This is interesting. I tested this out apparently at the same time as @mthalman. `tzdata-legacy` does work. Here is my Dockerfile... https://gist.github.com/lbussell/0146020f97fb5ea8249534bc92bcd69b

**Comment by richlander** [comment] 2024-11-22 17:56
I talked to @tarekgh. If I understood correctly, the globalization APIs look for the constructed path from the IANA name. There is no auto-conversion. That's the role the backwards compat package/path plays, which makes sense.

This is an ecosystem change. App code will need to be updated to the new names (or always install the compat package).

**Comment by tarekgh** [comment] 2024-11-24 20:03
To add, when doing `TimeZoneInfo.FindSystemTimeZoneById("FLE Standard Time")` , the .NET uses ICU to convert Windows timezone Id to IANA id which convert it to [Europe/Kiev](https://github.com/unicode-org/icu/blob/2ba362fa3b7cb8b4f4c35b016ec1c490e590b86a/icu4c/source/data/misc/windowsZones.txt#L254). You may [file a ticket to ICU](https://unicode-org.atlassian.net/jira/software/c/projects/ICU/issues) to let it do the mapping to the updated name `Europe/Kyiv` instead.

**Comment by lbussell** [comment] 2024-11-25 19:41
[Triage] Closing this as not planned since it's a change in the ICU package and not an issue with .NET. One workaround is to install the `tzdata-legacy` package from Ubuntu. The other workaround is to use `"Europe/Kyiv"` as the Time Zone ID directly.

**Closed by lbussell** 2024-11-25 19:41 UTC
Labels: untriaged

**Comment by mthalman** [comment] 2024-11-25 20:22
@tarekgh - I see this mapping: https://github.com/unicode-org/icu/blob/2ba362fa3b7cb8b4f4c35b016ec1c490e590b86a/icu4c/source/data/misc/timezoneTypes.txt#L48. Should that data be used in some way to handle this from the .NET side?

**Comment by tarekgh** [comment] 2024-11-25 22:08
@mthalman No. 

As I stated before we depend on the ICU API to do the mapping. The data you are pointing at is embedded inside ICU. If anything, it needs to change it will be in ICU. The .NET is not carrying any data for time zones.

**Comment by tarekgh** [comment] 2024-11-25 22:09
Linking some related issue talking about the mapping between Windows and ICU names.
https://github.com/tc39/proposal-canonical-tz/issues/16

**Comment by TrayanZapryanov** [comment] 2024-11-26 11:09
@lbussell Just a newbie question:
Do you have a sample how to install tzdata-legacy to chisseled image?
At the moment we use this docker file

FROM mcr.microsoft.com/dotnet/runtime:9.0.0-noble-chiseled-extra-amd64 AS base
WORKDIR /publish
COPY ./ContainerApp .
ENTRYPOINT ["dotnet", "XXX.dll"]
