### ISSUE TITLE
mcr.microsoft.com/dotnet/runtime:5.0-buster-slim contains ENV ASPNETCORE_URLS=http://+:80

### ISSUE THREAD

**Issue by juwens** [dotnet/dotnet-docker#2475] opened 2021-01-05 18:59 UTC
### Describe the Bug

Using the mentioned image from `https://hub.docker.com/_/microsoft-dotnet-runtime/`
 there is `ASPNETCORE_URLS=http://+:80` allways set.
 Which doesn't make sense in a non-aspnet-core runtime.

I would expect this ENV variable in `https://hub.docker.com/_/microsoft-dotnet-aspnet/`, but not in the "pure" runtime.

### Steps to Reproduce

```
docker pull mcr.microsoft.com/dotnet/runtime:5.0-buster-slim
docker inspect -f '{{.ContainerConfig.Env}}' mcr.microsoft.com/dotnet/runtime:5.0-buster-slim

output: 
[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin ASPNETCORE_URLS=http://+:80 DOTNET_RUNNING_IN_CONTAINER=true DOTNET_VERSION=5.0.1]
```

![image](https://user-images.githubusercontent.com/11560817/103686704-8712b580-4f8f-11eb-8e1b-c0f43b0d62d6.png)

### Other Information
This is only a minor inconvinience, nothing game-breaking.

### Output of `docker version`

```
C:\> docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.4
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:55:31 2020
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:58:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Output of `docker info`
```
C:\> docker info
Client: 
 Context:    default 
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.4.2-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 9
 Server Version: 20.10.0
 Storage Driver: overlay2
  Backing Filesystem: extfs 
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.921GiB
 Name: docker-desktop
 ID: NRXA:4FAT:RSFP:UECN:VGKV:CJVE:QFNH:GLLW:5ZEA:T5QQ:SR2L:O76I
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8 
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by MichaelSimons** [comment] 2021-01-06 19:32
This is a result of the image hierarchy.  This variable is [set in the `runtime-deps` image](https://github.com/dotnet/dotnet-docker/blob/master/src/runtime-deps/3.1/buster-slim/amd64/Dockerfile#L19) which is the basis for all of the .NET images.  It contains the native dependencies.  It is intended to run any type of self-contained app which is why the ASP.NET variable is included.  The side effect of this being set in the runtime image should not have any side-effects.

Closing as by design.

**Closed by MichaelSimons** 2021-01-06 19:32 UTC
Labels: bug, untriaged
