### ISSUE TITLE
SDK image 3.0.100-preview9 fails to publish on Azure Ubuntu 18 VMs

### ISSUE THREAD

**Issue by mikeharder** [dotnet/dotnet-docker#1294] opened 2019-09-05 01:40 UTC
## Steps to reproduce the issue
1. Create a new Azure VM with OS Ubuntu 18.04
2. Install updates (`sudo apt update`, `sudo apt full-upgrade`, `sudo reboot`)
3. Install docker (https://get.docker.com)
4. `git clone https://github.com/dotnet/dotnet-docker`
5. `cd dotnet-docker/samples/dotnetapp`
6. Modify the `Dockerfile` to use `sdk:3.0.100-preview9` instead of `sdk:2.2` (and `runtime:3.0.0-preview9` instead of `runtime:2.2`)
7. `docker build --pull -t dotnetapp .`

## Expected behavior
Builds

## Actual behavior
```
Step 11/19 : RUN dotnet publish -c Release -o out
 ---> Running in fa3592485007
Microsoft (R) Build Engine version 16.3.0-preview-19426-01+faf5e5d75 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 34.48 ms for /app/dotnetapp/dotnetapp.csproj.
  Restore completed in 34.48 ms for /app/utils/utils.csproj.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
/usr/share/dotnet/sdk/3.0.100-preview9-014004/Roslyn/Microsoft.CSharp.Core.targets(59,5): error MSB6004: The specified task executable location "/" is invalid. [/app/utils/utils.csproj]
The command '/bin/sh -c dotnet publish -c Release -o out' returned a non-zero code: 1
```

## Additional information
* Regression was introduced between `3.0.100-preview5` and `3.0.100-preview6` (repro steps succeed with `3.0.100-preview5`)
* Does not repro on a local Ubuntu 18.04 Server VM (created from the ISO download).
* Does not repro using `3.0.100-preview8` outside of Docker (installed via `snap`)
* Does repro with all flavors `-buster`, `-bionic`, and `-alpine`

## Output of `docker version`

```
Client: Docker Engine - Community                           
 Version:           19.03.2                                 
 API version:       1.40                                    
 Go version:        go1.12.8                                
 Git commit:        6a30dfc                                 
 Built:             Thu Aug 29 05:29:11 2019                
 OS/Arch:           linux/amd64                             
 Experimental:      false                                   
                                                            
Server: Docker Engine - Community                           
 Engine:                                                    
  Version:          19.03.2                                 
  API version:      1.40 (minimum version 1.12)             
  Go version:       go1.12.8                                
  Git commit:       6a30dfc                                 
  Built:            Thu Aug 29 05:27:45 2019                
  OS/Arch:          linux/amd64                             
  Experimental:     false                                   
 containerd:                                                
  Version:          1.2.6                                   
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:                                                      
  Version:          1.0.0-rc8                               
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:                                               
  Version:          0.18.0                                  
  GitCommit:        fec3683                                 
```

## Output of `docker info`

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 10
 Server Version: 19.03.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.0.0-1018-azure
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 13.67GiB
 Name: mikeharder-docker-test
 ID: L2CI:XKAM:WL3O:UUFW:T3EQ:QLCH:CGOR:7U4A:ORCL:JXFY:7VRN:ERQ7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by MichaelSimons** [comment] 2019-09-05 19:14
This appears to be a duplicate of https://github.com/dotnet/core/issues/3312 and https://github.com/dotnet/core/issues/3309

**Comment by MichaelSimons** [comment] 2019-09-05 19:15
The underlying issue is https://github.com/dotnet/corefx/issues/40850.

**Closed** 2019-09-05 19:16 UTC
