### ISSUE TITLE
microsoft/dotnet:2.2-runtime image dotnet runtime is also 2.2.0-preview-26820-02

### ISSUE THREAD

**Issue by liuhll** [dotnet/dotnet-docker#880] opened 2019-01-07 09:05 UTC
## Steps to reproduce the issue
1. I get the microsoft/dotnet:2.2-runtime  image from the docker hub and expect the .net runtime version of the built container to be 2.2.0,Instead of preview

## Actual behavior
![image](https://user-images.githubusercontent.com/16488441/50758852-53b4c780-129e-11e9-9b37-d51edb9c7f9d.png)

**Comment by MichaelSimons** [comment] 2019-01-07 14:33
I'm guessing you have an older preview image cached locally on your machine.  You have to explicitly pull to get the latest image.  Please try the following to see if it corrects your problem.

```
docker pull microsoft/dotnet:2.2-runtime
docker run --rm microsoft/dotnet:2.2-runtime dotnet --info
```

**Comment by Ben56** [comment] 2019-01-09 05:52
i have same issue,i run docker pull microsoft/dotnet:2.2-runtime     but   docker run --rm microsoft/dotnet:2.2-runtime dotnet --info    also   : 
Host (useful for support):
  Version: 2.2.0-preview-26820-02
  Commit:  b4726350b3

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.2.0-preview-26820-02 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:

**Comment by Ben56** [comment] 2019-01-09 05:54
i have two machine,another is good

**Comment by liuhll** [comment] 2019-01-09 05:55
you can pull `microsoft/dotnet:2.2.0-runtime`, this image is ok!

**Comment by Ben56** [comment] 2019-01-09 05:56
[root@S-CentOS7-001-LAN Common_Services]# docker run --rm microsoft/dotnet:2.2-runtime dotnet --infnfo
Unable to find image 'microsoft/dotnet:2.2-runtime' locally
2.2-runtime: Pulling from microsoft/dotnet
802b00ed6f79: Pull complete
44580ea7a636: Pull complete
73eebe8d57f9: Pull complete
895d2e8207cf: Pull complete
Digest: sha256:38177183674ece60e3cabb7605643b8876b78f1f1d0602155d15e311c6655f90
Status: Downloaded newer image for microsoft/dotnet:2.2-runtime

Host (useful for support):
  Version: 2.2.0-preview-26820-02
  Commit:  b4726350b3

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.2.0-preview-26820-02 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by Ben56** [comment] 2019-01-09 05:57
The reason I want to know the problem

**Comment by MichaelSimons** [comment] 2019-01-09 15:52
If you are seeing this issue, please include the output of `docker version` and `docker info` from the environment that reproduces the issue.

cc @Ben56, @liuhll

**Comment by Ben56** [comment] 2019-01-10 04:16
[root@S-CentOS7-001-LAN ~]# docker --version
Docker version 18.09.0, build 4d60db4
[root@S-CentOS7-001-LAN ~]# docker info
Containers: 22
 Running: 21
 Paused: 0
 Stopped: 1
Images: 106
Server Version: 18.09.0
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay weavemesh
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.1.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 4.685GiB
Name: S-CentOS7-001-LAN
ID: LEM7:344P:HNQX:QW5R:5K42:Y7XU:BMVD:JSAV:HRWC:ZLVX:ZIXJ:TVSQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: ben56
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://registry.docker-cn.com/
Live Restore Enabled: false
Product License: Community Engine

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
[root@S-CentOS7-001-LAN ~]#

**Comment by Ben56** [comment] 2019-01-10 04:17
but another machine is good ,  The same environment.

**Comment by liuhll** [comment] 2019-01-10 04:35
PS D:\workspace> docker --version
Docker version 18.09.0, build 4d60db4

PS D:\workspace> docker info
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 234
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155de2d02b
ID: ELBB:4GIN:6M3O:KUQN:PYST:D2IE:5V4V:SZGV:JQE7:OCI3:KP7W:EDQN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 54
 Goroutines: 71
 System Time: 2019-01-10T04:33:39.4404075Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 192.168.0.131
 127.0.0.0/8
Registry Mirrors:
 https://registry.docker-cn.com/
Live Restore Enabled: false
Product License: Community Engine

**Comment by Ben56** [comment] 2019-01-10 06:51
I found the cause of the problem:  
Registry Mirrors:
https://registry.docker-cn.com/

this  Mirror  problem,change another

**Comment by MichaelSimons** [comment] 2019-01-25 21:59
FYI - I've reached out to some folks at Docker to look into this problem with the China registry mirror.

**Comment by MichaelSimons** [comment] 2019-02-04 16:39
Docker has addressed the issue with the China registry mirror.  Closing.

**Closed by MichaelSimons** 2019-02-04 16:39 UTC
Labels: area:infrastructure, bug, triaged
