### ISSUE TITLE
Start-Job or pwsh does not work on the Alpine 3.18 images

### ISSUE THREAD

**Issue by cboulva99** [dotnet/dotnet-docker#4735] opened 2023-07-10 08:57 UTC
Hello,

I've tried to convert our existing system to an Alpine-based one.

However, it seems I'm having an issue:

Here it goes: I'm using the following image:
mcr.microsoft.com/dotnet/sdk:7.0-alpine3.18

The image seems to have pwsh installed, as if I run:
PS C:\> `docker run -it mcr.microsoft.com/dotnet/sdk:7.0-alpine3.18 pwsh`

I get:
```
PowerShell 7.3.4
PS />
```

However, once I'm there I cannot restart a new pwsh instance:
```
PS /> pwsh
ResourceUnavailable: Program 'pwsh' failed to run: An error occurred trying to start process '/usr/share/powershell/.store/powershell.linux.alpine/7.3.4/powershell.linux.alpine/7.3.4/tools/net7.0/any/pwsh' with working directory '/'. No such file or directoryAt line:1 char:1
+ pwsh
+ ~~~~.
```

nor use the Start-Job command:
```
PS /> Start-Job { Get-ChildItem }

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
3      Job3            BackgroundJob   Failed        False           localhost             Get-ChildItem
```

Thank you in advance for your time, 

Regards,

**Comment by mthalman** [comment] 2023-07-10 13:15
@adityapatwardhan - Can you investigate the root cause of this? Is this an installation issue in the Dockerfile or something specific to the behavior of PowerShell.

**Comment by cboulva99** [comment] 2023-07-10 13:25
Hello guys, for information, I've just tried using bullseye-slim image or jammy and i have no issue

**Comment by adityapatwardhan** [comment] 2023-07-10 17:22
I do have a workaround.. 

```
dotnet /usr/share/powershell/.store/powershell.linux.alpine/7.3.5/powershell.linux.alpine/7.3.5/tools/net7.0/any/pwsh.dll
```

**Comment by lbussell** [comment] 2023-07-10 17:32
I confirmed that this happens in `dotnet/sdk:7.0-alpine3.17` as well.

**Comment by adityapatwardhan** [comment] 2023-07-10 18:03
When we build the framework dependent pacakge, the apphost (pwsh.exe) is built for the platform it is built on. So, it is built for linux-x64. So this issue repros on all alpine images and not on linux-x64 based images.

**Comment by cboulva99** [comment] 2023-07-10 18:10
Thank you for this first analysis @adityapatwardhan .
Seems like getting pwsh to work properly has been an issue many times, what's puzzling is the fact that the first launch does in fact work propely.
As I added to my old ticket, we had the issue with the initial version of the .net 6.0 version  #3302  But then it was a powershell version mismatch, if I understand correctly

**Comment by mthalman** [comment] 2023-07-11 20:01
> is there any chance of getting this resolved in the next few days

I can speak to the updating of the .NET container images. These are updated on a monthly release schedule on the 2nd Tuesday of each month (today, in fact). So the soonest an update could occur is Aug 8, but that's only if PowerShell has released a fix by then.

@adityapatwardhan - Can you log an issue in the PowerShell repo so this gets tracked there since that's where the fix needs to be?

**Comment by adityapatwardhan** [comment] 2023-07-11 21:22
We can use this issue to track the work: https://github.com/PowerShell/PowerShell/issues/19703

It is substantial amount of work for us, as we need to build a new package which will have alpine compatible apphost.

As an easier workaround you can add a `pwsh` function as below:

```powershell
function pwsh ([string[]] $args) { dotnet /usr/share/powershell/.store/powershell.linux.alpine/7.3.5/powershell.linux.alpine/7.3.5/tools/net7.0/any/pwsh.dll $args }
```

**Comment by richlander** [comment] 2023-07-12 03:41
We should ensure that PowerShell correctly supports the full .NET SDK OS matrix. Workarounds are good as stop gaps.

**Comment by cboulva99** [comment] 2023-07-12 12:24
Ok, thank you for the information regarding the pwsh function, however, I don't see how I can launch a Start-Job nor a & command in this context, and we cannot modify the source scripts.
I mean, I don't see how I can launch a background job using the workaround. 

I've tried using this:
```
dotnet /usr/share/powershell/.store/powershell.linux.alpine/7.3.4/powershell.linux.alpine/7.3.4/tools/net7.0/any/pwsh.dll -c "Start-Job { ls }"

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
1      Job1            BackgroundJob   Failed        False           localhost             ls
```

But it still fails.
So I guess our only option is to use a bullseye-slim-based image.

By the way, the current version of the alpine3.18 image (`docker run -it mcr.microsoft.com/dotnet/sdk:7.0-alpine3.18 pwsh`) ( uses a 7.3.4 version of pwsh, not 7.3.5. The nightly image uses a 7.3.5 version though.

**Comment by cboulva99** [comment] 2023-07-12 13:18
BTW, I just tried with latest image (from yesterday), and looking at the Dockerfile, I've seen about the` /usr/share/powershell/pwsh` command.
This command DOES work, as it seems to be correctly configured for the Alpine release.

```
PS /usr/share/powershell> pwsh
ResourceUnavailable: Program 'pwsh' failed to run: An error occurred trying to start process '/usr/share/powershell/.store/powershell.linux.alpine/7.3.5/powershell.linux.alpine/7.3.5/tools/net7.0/any/pwsh' with working directory '/usr/share/powershell'. No such file or directoryAt line:1 char:1
+ pwsh
+ ~~~~.
PS /usr/share/powershell> ./pwsh
PowerShell 7.3.5
PS /usr/share/powershell> ./pwsh
PowerShell 7.3.5
PS /usr/share/powershell> $PSHOME
/usr/share/powershell/.store/powershell.linux.alpine/7.3.5/powershell.linux.alpine/7.3.5/tools/net7.0/any
PS /usr/share/powershell>
```

I can't help myself but wonder, why don't $PSHOME point on` /usr/share/powershell`, instead of `/usr/share/powershell/.store/powershell.linux.alpine/7.3.5/powershell.linux.alpine/7.3.5/tools/net7.0/any`?

**Comment by adityapatwardhan** [comment] 2023-07-17 23:39
This PR should fix this: https://github.com/PowerShell/PowerShell/pull/19995

It will take some time for us to release an integrate into dotnet-docker

**Comment by mthalman** [comment] 2023-08-09 18:39
This is a duplicate of https://github.com/dotnet/dotnet-docker/issues/1922

**Closed by mthalman** 2023-08-09 18:39 UTC
Labels: bug, area-dockerfiles
