### ISSUE TITLE
`tzdata` shouldn't be in `azurelinux3.0-distroless`, but just in `-extra` like for `chiseled`?

### ISSUE THREAD

**Issue by mathieu-benoit** [dotnet/dotnet-docker#5888] opened 2024-09-14 18:10 UTC
According to https://github.com/dotnet/dotnet-docker/blob/main/documentation/distroless.md#how-do-i-use-globalization-with-distroless-images and https://github.com/dotnet/dotnet-docker/issues/4804#issuecomment-1677916434, the 2 `distroless` flavors should not have `tzdata` and `icu` in `<default>`/`-aot`, but just in `-extra`.

But if we run `syft mcr.microsoft.com/dotnet/runtime-deps:8.0.8-azurelinux3.0-distroless`, we could see `tzdata` in there:
```
├── ✔ Packages                        [13 packages]  
   └── ✔ Executables                     [43 executables]  
NAME                         VERSION               TYPE   
azurelinux-release           3.0-18.azl3           rpm     
distroless-packages-minimal  3.0-5.azl3            rpm     
filesystem                   1.1-21.azl3           rpm     
glibc                        2.38                  rpm     
glibc                        2.38-7.azl3           rpm     
libgcc                       13.2.0-7.azl3         rpm     
libstdc++                    13.2.0-7.azl3         rpm     
openssl                      3.3.0                 rpm     
openssl-libs                 3.3.0-2.azl3          rpm     
prebuilt-ca-certificates     2501981:3.0.0-7.azl3  rpm     
tzdata                       2024a-1.azl3          rpm     
zlib                         1.3.1                 rpm     
zlib                         1.3.1-1.azl3          rpm
```
Same with:
- `mcr.microsoft.com/dotnet/nightly/runtime-deps:8.0.8-azurelinux3.0-distroless-aot`
- `mcr.microsoft.com/dotnet/runtime-deps:9.0.0-rc.1-azurelinux3.0-distroless`
- `mcr.microsoft.com/dotnet/nightly/runtime-deps:9.0.0-rc.1-azurelinux3.0-distroless-aot`

`chiseled` doesn't have this issue though, `tzdata` is just in `-extra`, not in `<default>`/`-aot`.

Is that expected or a bug?

**Comment by mathieu-benoit** [comment] 2024-09-14 18:22
It was apparently directly added in upstream `azurelinux` from there: https://github.com/microsoft/azurelinux/pull/4247?

**Comment by lbussell** [comment] 2024-09-16 16:32
Yes, this is the expected behavior. We won't remove packages from the upstream image as that would be an unnecessary diff. However we do not install or update the `tzdata` package during our build. We try very hard to prevent breaking changes, but since we don't control upstream images, you should not assume that `tzdata` will always exist in `azurelinux3.0-distroless` images. If your app relies on `tzdata` you should take an explicit dependency on it by using the `-extra` variant.

Closing as not planned since this is expected behavior.

**Closed by lbussell** 2024-09-16 16:32 UTC
Labels: bug, area-infrastructure, untriaged
