### ISSUE TITLE
sqlserver Database connectivity issues

### ISSUE THREAD

**Issue by king311247** [dotnet/dotnet-docker#1385] opened 2019-10-12 09:22 UTC
1.use sqlserver2012
2.an app develop by aspnetcore3.0 and deploy on docker (base image:mcr.microsoft.com/dotnet/core/aspnet:3.0) 
3. `fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLQETE13F55E", Request id "0HLQETE13F55E:0000000C": An unhandled exception was thrown by the application.
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, ArraySegment`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)`

4.when i use mcr.microsoft.com/dotnet/core/aspnet:2.1  ,my app can run successfuly. because the tls version is not set in /etc/ssl/openssl.cnf  but it's set TLSv1.2 in /etc/ssl/openssl.cnf 
![QQ截图20191012172128](https://user-images.githubusercontent.com/10952874/66698918-d75f8100-ed14-11e9-9e9c-3067b383bb29.png)

**Comment by MichaelSimons** [comment] 2019-10-14 13:31
Closing as a duplicate of dotnet/SqlClient#222.

**Closed by MichaelSimons** 2019-10-14 13:31 UTC
