### ISSUE TITLE
Can't connect to sql server from docker

### ISSUE THREAD

**Issue by itdoster** [dotnet/dotnet-docker#1355] opened 2019-09-30 13:16 UTC
## Steps to reproduce the issue
1. Run .net core 3 app in docker in release mode
2. When app trying to make sql query - it's freezing
3. When run without docker - works fine

## Output of `docker version`

```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

## Output of `docker info`

```
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 1
  Paused: 0
  Stopped: 5
 Images: 58
 Server Version: 19.03.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 1.952GiB
 Name: docker-desktop
 ID: 4TQW:BHXU:UMCG:LYRB:3RJN:NXN4:TGE6:BZIB:6VMQ:KE65:KUJP:C4QC
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 36
  Goroutines: 50
  System Time: 2019-09-30T13:17:46.795787402Z
  EventsListeners: 2
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

```

**Comment by MichaelSimons** [comment] 2019-09-30 14:17
This seems like a duplicate of https://github.com/dotnet/SqlClient/issues/222.  There are a couple workarounds - switch to use a non-buster based image or change the openssl SECLEVEL to 1.

**Comment by itdoster** [comment] 2019-09-30 14:25
@MichaelSimons thanks!

**Comment by MichaelSimons** [comment] 2019-10-02 18:28
Closing as a duplicate of dotnet/SqlClient#222.

**Closed by MichaelSimons** 2019-10-02 18:28 UTC
