### ISSUE TITLE
aspnetcore:3.0 docker image and sqlclient issue

### ISSUE THREAD

**Issue by justinweinberg** [dotnet/dotnet-docker#1289] opened 2019-08-29 01:51 UTC
## Steps to reproduce the issue
1. Setup a SQL Server to force SSL connections 
2.  Setup a small project that opens a connection to the SQL Server 
3. Build the project in a container and run with asp.net 3.0

My docker file is as follows:

```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build-env
WORKDIR /app

# Copy csproj files, sln, and restore as distinct layers
COPY api/*.sln .
COPY api/Minimal.API/Minimal.API.csproj ./Minimal.API/
RUN dotnet restore

# Copy everything else and build
COPY api/. ./
RUN dotnet publish -c Release -o out

FROM base AS final
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "Minimal.API.dll"]
```

My Program.cs code

```
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
 using System.Data.SqlClient;

namespace foo
{
    public class Program
    {
        public static void Main(string[] args)
        {
           var conn = "YOUR CONNECTION HERE";
           System.Console.WriteLine("hello world");
           using (var connection = new SqlConnection(conn))
                {
                	System.Console.WriteLine("opening connection");
                    connection.Open();
                    System.Console.WriteLine("Opened connection");
                }


        }

    
    }
}
```

## Expected behavior
The connection should work (It works fine on Windows and Mac with the actual dotnet bits installed for 3.0)

## Actual behavior
Connection Hangs.  

## Additional information (e.g. issue happens only occasionally)
Happens every time

## Output of `docker version`
Docker version 18.06.0-ce, build 0ffa825

## Output of `docker info`
$ docker info
Containers: 19
 Running: 2
 Paused: 0
 Stopped: 17
Images: 38
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d83b31c
ID: MN5P:4XMH:6J65:PH4V:YERJ:X6BA:236J:P6AG:L5IH:SNKW:BJWH:BPF3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 39
 Goroutines: 77
 System Time: 2019-08-29T01:48:11.7997771Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by MichaelSimons** [comment] 2019-09-04 18:36
@justinweinberg - Where is the SQL server located?  Is it on the Docker host machine?  Can you provide the connection string excluding any private data?  What diagnostic steps have you done to this point?  Does this test app work on the Docker host machine?  Where is the hang in the test app?

**Comment by justinweinberg** [comment] 2019-09-05 22:39
Hi Michael.  Thanks for looking into this.

The SQL Server is in an instance in AWS RDS  with ForceSSL set to true.  I tried a number of different endpoints with the same configuration and all exhibited the same inability to connect. 

The connection string with the sensitive bits removed is below 

`***.***.us-west-2.rds.amazonaws.com,1433;Initial Catalog=***;User ID=***;password=***;`

I realize now I didn't tell it to use SSL but I didn't have to in the past.

**Diagnostics** 

-  I was able to connect to a self hosted SQL Server that did not have force SSL enabled without issue.
- I verified I could telnet to port 1433 in both setups.  I tried the connection strings with both  
- I attempted to prove that the issue is not in .NET core 3 itself by replicating the connection issue with Python using PyODBC. I had the same behavior in that I could not connect to AWS RDS with ForceSSL to true using a simple PyODBC example.  I was able to connect to the self hosted SQL Server 
-.  The same code and connection strings work fine in .NET Core 2.2 with the aspnetcore container.

My theory is  that the 3.0 Docker image either has an openssl / odbc configuration issue or is missing a certificate that the 2.1 container had by default or is unable to obtain the cert automatically.

**Comment by justinweinberg** [comment] 2019-09-05 22:45
I should add as stated in the original bug report it works fine on windows and mac from outside the container connecting to the same AWS RDS endpoint with Force SSL, so it's probably not connection string related

**Comment by MichaelSimons** [comment] 2019-09-11 18:44
I believe one difference is the container OS between 2.2 and 3.0.  `mcr.microsoft.com/dotnet/core/aspnet:3.0` is based on buster-slim while `mcr.microsoft.com/dotnet/core/aspnet:2.2` is based on stretch-slim.  This would be a good place to look for differences.

**Comment by MichaelSimons** [comment] 2019-09-25 18:54
@justinweinberg - did you get a chance to investigate this?  Did you compare the certificates between the two base images?

**Comment by justinweinberg** [comment] 2019-09-25 19:14
I have not.  We resolved to just use .NET Core 2.1 for now.

Thanks,

Justin

**Comment by gudang** [comment] 2019-09-26 09:07
try change Ubuntu base image in docker (ie. bionic). Works in my machine, but I don't use SSL connection.

**Comment by MichaelSimons** [comment] 2019-09-26 20:40
This seems to be a duplicate of https://github.com/dotnet/SqlClient/issues/222.  Workarounds would be to use the ubuntu or alpine images or to downgrade the OpenSSL TLS security level from 2 to 1 in the buster-slim image.

**Comment by MichaelSimons** [comment] 2019-10-02 18:40
Closing as a duplicate of dotnet/SqlClient#222.

**Closed by MichaelSimons** 2019-10-02 18:40 UTC
