### ISSUE TITLE
Culture missing (fr...) for ASP.NET Core Runtime 3.1 

### ISSUE THREAD

**Issue by using-system** [dotnet/dotnet-docker#3854] opened 2022-06-16 13:34 UTC
### Describe the Bug

 CultureInfo.GetCultures(CultureTypes.AllCultures) return only EN culture since the last build.

### Steps to Reproduce

```
# build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine
```

Then in .net code --> CultureInfo.GetCultures(CultureTypes.AllCultures) returns only en cultures.

It's working with the previous image (mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine@sha256:1fd90b0b0b640f598a77dad2e4c51b101c59c9994b4c2ee92189911eab2fb3f2)

**Comment by mthalman** [comment] 2022-06-16 13:36
Duplicate of https://github.com/dotnet/dotnet-docker/issues/3844

This has just been republished with the fix within the past hour. If you pull the `3.1-alpine` tag, it should resolve your issue.

**Closed by mthalman** 2022-06-16 13:36 UTC
Labels: bug, area-dockerfiles, untriaged

**Comment by mthalman** [comment] 2022-06-16 13:38
Oh, sorry, that's for sdk images only. I see you're using the aspnet image. Can you show your whole Dockerfile?

**Comment by using-system** [comment] 2022-06-16 13:39
# Generate runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine

# Solve Globalization Invariant Mode is not supported on Alpine
# See https://github.com/dotnet/SqlClient/issues/220
RUN apk add --no-cache icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
ENV DOTNET_RUNNING_IN_CONTAINER=true


# Add a new user "web" with user id 8877
RUN adduser -u 8877 -D web

# Change to non-root privilege
USER 8877

LABEL company="***"

WORKDIR /app
EXPOSE 8080/tcp
COPY --from=build /app/out .

ENTRYPOINT [ "dotnet", "***.dll" ]

**Comment by mthalman** [comment] 2022-06-16 13:43
Right, so your problem is this line:

```Dockerfile
RUN apk add --no-cache icu-libs
```

You can read through https://github.com/dotnet/dotnet-docker/issues/3844 for context. But since the `3.1-alpine` has been moved to Alpine 3.16, you're now affected by the [ICU data split](https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.16.0#ICU_data_split). To resolve this, you'll need to also install the `icu-data-full` package in addition to `icu-libs`:

```Dockerfile
RUN apk add --no-cache icu-data-full icu-libs
```
