### ISSUE TITLE
Tools home missing from path on alpine

### ISSUE THREAD

**Issue by Leandowich** [dotnet/dotnet-docker#615] opened 2018-07-03 15:06 UTC
## Steps to reproduce the issue
1. FROM microsoft/dotnet:2.1-sdk-alpine
2. RUN dotnet tool install --global dotnet-sonarscanner
3. RUN dotnet sonarscanner

## Expected behavior

```
You can invoke the tool using the following command: dotnet-sonarscanner
Tool 'dotnet-sonarscanner' (version '4.3.1') was successfully installed.
```

## Actual behavior

```
Tools directory '/root/.dotnet/tools' is not currently on the PATH environment variable.
If you are using bash, you can add it to your profile by running the following command:

cat << \EOF >> ~/.bash_profile
# Add .NET Core SDK tools
export PATH="$PATH:/root/.dotnet/tools"
EOF

You can add it to the current session by running the following command:

export PATH="$PATH:/root/.dotnet/tools"

You can invoke the tool using the following command: dotnet-sonarscanner
Tool 'dotnet-sonarscanner' (version '4.3.1') was successfully installed.
```

Followed by:

`No executable found matching command "dotnet-sonarscanner"`

## Output of `docker version`

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

## Output of `docker info`

```
Containers: 62
 Running: 0
 Paused: 0
 Stopped: 62
Images: 276
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d05dd01
ID: P7WE:Y5JD:KATN:4PST:LNZO:3WUL:QVWN:76PM:NPA3:BJXD:GONY:W6SS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 36
 System Time: 2018-07-03T15:03:19.4938297Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by MichaelSimons** [comment] 2018-07-03 16:06
This is a duplicate of https://github.com/dotnet/dotnet-docker/issues/520.

**Comment by MichaelSimons** [comment] 2018-07-11 17:03
Closing as a duplicate of #520.

**Closed by MichaelSimons** 2018-07-11 17:03 UTC
Labels: area:dockerfiles, duplicate, triaged
