### ISSUE TITLE
Unable to run VS project on Docker due to issue with PrepareForLaunch task

### ISSUE THREAD

**Issue by bartekmp** [dotnet/dotnet-docker#211] opened 2017-02-23 19:56 UTC
I am having trouble with launching .NET Core project on Docker container. When I try to launch even the default, basic ASP.NET Core project, it fails.

I can see that the issue is related to the name of user directory on my Windows - it's something like "User Name", with a space in the middle. I possibly could fix that issue just with putting the GetClrDbg.ps1 path into quotes but it's not that easy. Is this expected behaviour?

The error log says:

```
MSB4018	The "PrepareForLaunch" task failed unexpectedly.
Microsoft.DotNet.Docker.CommandLineClientException: C:\Users\User: The term 'C:\Users\User' is not recognized as the name of a cmdlet, function, script file, or ope
rable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again
.
At line:1 char:1
+ C:\Users\User Name\AppData\Local\Temp\GetClrDbg.ps1 -Version 'VS ...
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\User:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Docker.DockerWorkspace.<EnsureDebuggerExistsAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Docker.BuildTasks.PrepareForLaunch.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Docker.BuildTasks.DockerBaseTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

## Steps to reproduce the issue

1. Launch VS2015
2. Create ASP.NET Core Web App
3. Launch Docker debugging

## Expected behavior

Application runs and allows its debugging.

## Actual behavior

Build fails due to error mentioned above.

## Additional information

- OS: Windows 10
- IDE: VS 2015 Update 3

## Output of `docker version`

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

## Output of `docker info`

```
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 22
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 74
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.8-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.837 GiB
Name: moby
ID: 3J3N:LTKH:HDJ7:JHPJ:PR6T:JKM7:VDXA:KVPS:QSZC:O3AT:4VXM:O4YO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 25
 Goroutines: 30
 System Time: 2017-02-18T10:30:08.7071445Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by MichaelSimons** [comment] 2017-02-27 15:24
@dazhao-msft, @SteveLasker - this looks related to VS Docker Tooling.  Can you please respond?

**Comment by himadrinath** [comment] 2017-03-03 19:12
same problem for me

**Comment by dazhao-msft** [comment] 2017-03-08 00:02
This is a known issue in VS 2015. We have fixed the issue in VS 2017, which just got released RTW today: https://www.visualstudio.com/. 

Besides that, we have improved the Docker tools for Visual Studio significantly in VS 2017. I'd suggest you move to use VS 2017 instead.

**Comment by bartekmp** [comment] 2017-03-08 00:06
Thanks for letting us know that it's fixed in new version of VS. However I'm not interested so far in switching to VS2017, as I find VS2015 stable and I'm not responsible for updating my computer's software. Please, tell me, is this really so huge deal to not to make it work on VS2015?

**Comment by dazhao-msft** [comment] 2017-03-08 00:18
There won't be any update for VS 2015 any more since VS 2017 just got released. 

Try this as a workaournd in a PowerShell command line:

```PowerShell
C:\Users\User Name\AppData\Local\Temp\GetClrDbg.ps1 -Version latest -RuntimeID debian.8-x64 -InstallPath "C:\Users\User Name\clrdbg"
```

Once the clrdbg is in place, VS will skip downloading it again next time.

**Comment by MichaelSimons** [comment] 2017-03-08 14:22
Closing per @dazhao-msft comments.

**Closed by MichaelSimons** 2017-03-08 14:22 UTC

**Comment by SteveLasker** [comment] 2017-03-09 14:28
@bartekmp, we do appreciate your concern the ownership and impact of change. 
Please see this post for how we're thinking about container tooling:
https://blogs.msdn.microsoft.com/stevelasker/2016/11/22/visual-studio-docker-tools-support-for-visual-studio-2015-2017/

**Comment by ozitraveller** [comment] 2017-03-13 22:56
I'm using VS 2017 and I'm getting MSB4018	The "PrepareForLaunch" task failed unexpectedly.

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "PrepareForLaunch" task failed unexpectedly.
Microsoft.DotNet.Docker.CommandLineClientException: Creating dockercompose1767308851_ms.smartreports.reportname_1
ERROR: for ms.smartreports.reportname  Cannot start service testproject: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/C/Users/userBob/clrdbg\\\" to rootfs \\\"/var/lib/docker/aufs/mnt/eddaa7a50c761c1e25712505370f52003848ed0a69afee98e742b092342c7568\\\" at \\\"/clrdbg\\\" caused \\\"stat /C/Users/userBob/clrdbg: input/output error\\\"\""
Encountered errors while bringing up the project..

For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting ---> Microsoft.DotNet.Docker.CommandLineClientException: Creating dockercompose1767308851_testproject_1
ERROR: for testproject  Cannot start service testproject: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/C/Users/userBob/clrdbg\\\" to rootfs \\\"/var/lib/docker/aufs/mnt/eddaa7a50c761c1e25712505370f52003848ed0a69afee98e742b092342c7568\\\" at \\\"/clrdbg\\\" caused \\\"stat /C/Users/userBob/clrdbg: input/output error\\\"\""
Encountered errors while bringing up the project.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Docker.DockerComposeClient.<ExecuteAsync>d__18.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.Docker.DockerComposeClient.<ExecuteAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Docker.DockerWorkspace.<PrepareForLaunchAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Docker.BuildTasks.DockerBaseTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets	192

**Comment by dazhao-msft** [comment] 2017-03-14 00:03
@ozitraveller , this is typically caused by volume sharing of Docker for Windows not working properly. Can you try resetting credentials and re-enable the shared drives?

**Comment by ozitraveller** [comment] 2017-03-14 00:06
awesome dazhao thanks fixed.

**Comment by SrivatsaMarichi** [comment] 2017-04-25 09:43
I'm using VS 2017 and I get this error when I run too.

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "PrepareForLaunch" task failed unexpectedly.
Microsoft.DotNet.Docker.CommandLineClientException: Building partsunlimitedwebsite
Service 'partsunlimitedwebsite' failed to build: expected HTTP 206 from byte range request.

For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting ---> Microsoft.DotNet.Docker.CommandLineClientException: Building partsunlimitedwebsite
Service 'partsunlimitedwebsite' failed to build: expected HTTP 206 from byte range request
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Docker.DockerComposeClient.<ExecuteAsync>d__18.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.Docker.DockerComposeClient.<ExecuteAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Docker.DockerWorkspace.<PrepareForLaunchAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Docker.BuildTasks.DockerBaseTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets	192

**Comment by djroughhouse** [comment] 2017-05-12 00:54
I had this issue in VS2017, it was as @dazhao-msft said, the drive share was not enabled in the Docker for Windows settings.

**Comment by zawtunit** [comment] 2018-06-30 07:48
I also same problem VS2017 Community.. Kindly advise what to do

**Comment by MichaelSimons** [comment] 2018-07-02 13:34
In order to get the best help, please post any questions related to the VS Docker tooling to their repo - https://github.com/Microsoft/DockerTools/issues.  This repo is specific to the microsoft/dotnet, microsoft/dotnet-nightly, and microsoft/dotnet-samples Docker images.
