### ISSUE TITLE
Why are dotnet-* tools not out of the box available in the docker images for .NET CORE

### ISSUE THREAD

**Issue by bjarkenator** [dotnet/dotnet-docker#1737] opened 2020-03-11 13:09 UTC
Hi,  we wonder why dotnet-trace, dotnet-symbols, dotnet-counters are not part of the docker image for .NET CORE ? 
We are a shop with K8S onsite, and without any internet connection, hence we need to prefab the images constantly with the correct tooling.

//Bjarke

**Comment by MichaelSimons** [comment] 2020-03-11 18:16
@bjarkenator - Can you please explain your usage scenario in more detail?  Are you using the sdk image as an interactive dev container?

**Comment by bjarkenator** [comment] 2020-03-19 03:48
The scenario is that if we have 1000s of pods - and we experience one is misbehaving somehow - and we run .Dotnet core 3.1 - and the .net processes fx. are looping heavilvy, or GC constantly - and I cannot reproduce the issue on my windows machine with Visual Studio - but I get this misbehaving pod now and then...what do I do then ? Well, if I had dotnet-trace inside the pods image - i could log into the pod, do a dotnet-trace, move the file to my windows machine and load it in perfview - so i might see whith hot stacks there are, or which parts of the .NET casues the GC.

**Comment by MichaelSimons** [comment] 2020-04-01 01:36
This appears to be a duplicate of https://github.com/dotnet/dotnet-docker/issues/1672.

**Comment by MichaelSimons** [comment] 2020-04-01 01:37
This is related to https://github.com/dotnet/dotnet-docker/issues/1672.

**Comment by MichaelSimons** [comment] 2020-04-01 01:43
As mentioned in #1672, dotnet global tools would require the SDK which would severely bloat the runtime images.  We continuous receive feedback that maintaining minimal runtime images is important to our users.  The preferred approach for using dotnet-trace would be to run it in a sidecar container.  dotnet/diagnostics#810 tracks this work.

**Comment by MichaelSimons** [comment] 2020-04-03 15:53
@bjarkenator - Thanks for your feedback on the .NET Core images.  I mentioned in my [previous response](https://github.com/dotnet/dotnet-docker/issues/1737#issuecomment-606976785) that we feel dotnet-trace is best used in a side-car container for your type of scenario.  Can you provide the usage scenarios you would like to use dotnet-symbols and dotnet-counters in?

**Comment by MichaelSimons** [comment] 2020-04-08 18:44
Closing as the primary scenario of utilizing dotnet-trace is tracked with dotnet/diagnostics#810.  Feel free to provide usage scenarios for other dotnet- tools in the runtime images.

**Closed by MichaelSimons** 2020-04-08 18:44 UTC
