### ISSUE TITLE
Root certificate for postgres database is missing

### ISSUE THREAD

**Issue by epaulsen** [dotnet/dotnet-docker#6071] opened 2024-11-20 21:42 UTC
### Describe the bug

After upgrading to .net 9, our docker containers that use Azure postgres database cannot connect to the database, claiming there is a validation error in the certificate chain.  We use `VerifyFull` in our connection string for the database, and TLS 1.2 is turned on in the postgres instance.

Example dockerfile:
```
FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine AS runtime

COPY ./out .

EXPOSE 8080

ENTRYPOINT ["dotnet", "MyApp.dll"]
```
[There is documentation on the required custom certificate here](https://learn.microsoft.com/en-us/previous-versions/azure/postgresql/single-server/concepts-ssl-connection-security#applications-that-require-certificate-verification-for-tls-connectivity)
[And here](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-networking-ssl-tls#configure-ssl-on-the-client)

The certificate chain looks like this:
```
[0] CN=cr18.westeurope1-a.control.database.windows.net, O=Microsoft Corporation, L=Redmond, S=WA, C=US
[1] CN=Microsoft Azure RSA TLS Issuing CA 03, O=Microsoft Corporation, C=US
[2] CN=DigiCert Global Root G2, OU=www.digicert.com, O=DigiCert Inc, C=US
```

### Which .NET image(s) are you using?

mcr.microsoft.com/dotnet/aspnet:9.0-alpine (but I think all .net 9 images are affected)

### Steps to reproduce

Prerequisites: Azure Postgres flexible or single server with TLS1.2 required, and dotnet 9 sdk installed on your machine

I've created a minimal repro in this repository: [https://github.com/epaulsen/minimal-repro-cert-issue](https://github.com/epaulsen/minimal-repro-cert-issue)

Clone the repository, and do 
```
dotnet run -- "Host=<YOUR_AZURE_DB>.postgres.database.azure.com;Database=<YOUR_DATABASE>;Port=5432;Username=<USERNAME>;Password=<PASSWORD>;SSL Mode=VerifyFull"
```
This runs the code locally on your machine, and it works as expected.

To repro the bug, run the same app in a basic .net 9 container:
```
dotnet publish --os linux --arch x64 /t:PublishContainer
docker run minimal-repro:latest "<same connection string as in example above"
```
*Expected*
Same outcome as with `dotnet run`

*Actual*
```
Unhandled exception. Npgsql.NpgsqlException (0x80004005): Exception while performing SSL handshake
 ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
   at System.Net.Security.SslStream.SendAuthResetSignal(ReadOnlySpan`1 alert, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.NegotiateEncryption(SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.NegotiateEncryption(SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.RawOpen(SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|214_1(NpgsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.PoolingDataSource.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.PoolingDataSource.<Get>g__RentAsync|33_0(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|42_0(Boolean async, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in D:\git\github\minimal-repro-cert-issue\Program.cs:line 14
   at Program.<Main>(String[] args)
```

### Other information

This was working just fine with .net 8 base images, but not with .net 9 images.

### Output of `docker version`

```console
Docker version 27.3.1, build ce12230
```

### Output of `docker info`

```console
Client:
 Version:    27.3.1
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.37
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.15
    Path:     C:\Program Files\Docker\cli-plugins\docker-desktop.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.27
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.14.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 10
  Running: 0
  Paused: 0
  Stopped: 10
 Images: 18
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 472731909fa34bd7bc9c087e4c27943f9835f111
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.167.4-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.48GiB
 Name: docker-desktop
 ID: 351c7fa3-b9ef-49bf-8149-a57824d36e26
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=npipe://\\.\pipe\docker_cli
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

**Comment by richlander** [comment] 2024-11-20 23:00
Can you reproduce this on Alpine using wget or curl?

**Comment by skogsaas** [comment] 2024-11-21 07:13
Hi, colleague of @epaulsen here 👋 

I've checked one of the latest builds we have in production using .NET 8 base images, built yesterday using Azure DevOps hosted agents:

docker inspect:
```
"Created": "2024-11-20T12:26:11.654539717Z",
...

"image.base.digest": "sha256:a0062262fd674573be2314890006acadfd233fd7fdf89b3a5f44694b7632b29e",
"image.base.ref.name": "mcr.microsoft.com/dotnet/aspnet:8.0-alpine"
```

**Comment by epaulsen** [comment] 2024-11-21 08:07
> Can you reproduce this on Alpine using wget or curl?

No.  Not sure about how the intrisics of postgres works, but the endpoint is not an http/https endpoint. 
I get the same curl error when trying to do `curl -v <endpoint>` from both my desktop, Ubuntu WSL2 and net8/net9 alpine image.


> > This was working just fine with .net 8 base images, but not with .net 9 images.
> 
> Can you validate that you build with `--pull` for your .NET 8 images? It is important to validate that you are using the same Alpine build.

Did a manual `docker system prune --all` and then `docker build --pull` on our .net8 production images.
The image created works as expected, so this is definitely a regression in .net images between `8.0-alpine` and `9.0-alpine`.

**Comment by richlander** [comment] 2024-11-21 15:55
Thanks for the additional clarity. We're going to find the best person to investigate this.

**Comment by richlander** [comment] 2024-11-21 16:41
Do you have a small repro you can share? Also, can you repro it on your desktop OS?

**Comment by lbussell** [comment] 2024-11-21 16:48
> Do you have a small repro you can share? Also, can you repro it on your desktop OS?

@richlander there is a repro repo + Dockerfile in the issue body.

**Comment by richlander** [comment] 2024-11-21 16:52
> > Do you have a small repro you can share? Also, can you repro it on your desktop OS?
> 
> [@richlander](https://github.com/richlander) there is a repro repo + Dockerfile in the issue body.

Ooops. Reading continues to be a challenge for me!

**Comment by roji** [comment] 2024-11-21 16:53
Yes, there's a known issue with Npgsql 9.0 around VerifyFull/VerifyCA, see https://github.com/npgsql/npgsql/issues/5942. tl;dr a fix has already been merged, and will be out with 9.0.2; we're waiting just a bit before releasing that, in case other critical issues are reported.

In the meantime, you're welcome to use the 9.0.2 daily build by adding [the Npgsql patch nuget feed](https://www.npgsql.org/doc/installation.html#daily-builds), and referencing at least version 9.0.2-ci.20241120T173808.

**Comment by richlander** [comment] 2024-11-21 17:07
Certainly, testing the patch would be greatly appreciated!

**Comment by epaulsen** [comment] 2024-11-22 05:44
> Do you have a small repro you can share? Also, can you repro it on your desktop OS?
 

Like I said initially, does not repro on my desktop.

`dotnet run <connectionstring>` works on my desktop(win 11)

`docker run <container> -- <connectionstring` works for .net8, but fails for .net9.

**Comment by richlander** [comment] 2024-11-23 00:08
Did you test with the latest patch, in the 9.0.2 daily build?

**Comment by epaulsen** [comment] 2024-11-24 10:30
> Did you test with the latest patch, in the 9.0.2 daily build?

No, haven't had time to do that, sorry.

**Comment by lbussell** [comment] 2024-11-25 19:33
[Triage] Closing as not planned since this is not an issue with .NET container images. The npgsql issue is tracked by https://github.com/npgsql/npgsql/issues/5942.

**Closed by lbussell** 2024-11-25 19:33 UTC
Labels: area-external, untriaged
