### ISSUE TITLE
.NET 7 Segmentation fault while throwing Exceptions using alpine image

### ISSUE THREAD

**Issue by mario-zelger** [dotnet/dotnet-docker#4465] opened 2023-02-28 14:08 UTC
### Describe the Bug
*Not 100% sure if this is the right repo to report this or if it concerns another .NET repository*

Throwing Exceptions leads to a `Segmentation fault` when using the .NET 7 `alpine` images. This was tested with as simple console app and ASP.NET app using the `mcr.microsoft.com/dotnet/runtime:7.0-alpine` or `mcr.microsoft.com/dotnet/aspnet:7.0-alpine` image respectively. Using non alpine images, the Exception is displayed on the console and the program is aborted as expected.

The issue first appeared inside a ASP.NET container in a Kubernetes cluster but the tests described here were done with Docker Desktop for Windows.

```powershell
PS C:\docker> docker run --rm mcr.microsoft.com/dotnet/runtime:7.0 uname -a
Linux 8d7a60d9961d 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 GNU/Linux

PS C:\docker> docker run --rm mcr.microsoft.com/dotnet/runtime:7.0-alpine uname -a
Linux 6fdff5750a9f 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 Linux
```

```powershell
PS C:\docker> docker run --rm mcr.microsoft.com/dotnet/aspnet:7.0 uname -a
Linux f73dba2d3c73 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 GNU/Linux

PS C:\docker> docker run --rm mcr.microsoft.com/dotnet/aspnet:7.0-alpine uname -a
Linux 4dea4f49d265 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 Linux
```

#### Console App
`SegmentationFault.csproj`
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>
```

`Program.cs`
```csharp
Console.WriteLine("Hello, World!");
throw new Exception("some exception");
```

`Dockerfile`
```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["SegmentationFault/SegmentationFault.csproj", "SegmentationFault/"]
RUN dotnet restore "SegmentationFault/SegmentationFault.csproj"
COPY . .
WORKDIR "/src/SegmentationFault"
RUN dotnet build "SegmentationFault.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SegmentationFault.csproj" -c Release -o /app/publish


#FROM mcr.microsoft.com/dotnet/runtime:7.0
FROM mcr.microsoft.com/dotnet/runtime:7.0-alpine

WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT /bin/sh
```

##### Output with `mcr.microsoft.com/dotnet/runtime:7.0-alpine`
```powershell
PS C:\docker> docker run --rm -it segmentation-fault-console:alpine
/app # dotnet SegmentationFault.dll
Hello, World!
Segmentation fault
/app #
```

##### Output with `mcr.microsoft.com/dotnet/runtime:7.0`
```powershell
PS C:\docker> docker run --rm -it segmentation-fault-console:latest
# dotnet SegmentationFault.dll
Hello, World!
Unhandled exception. System.Exception: some exception
   at Program.<Main>$(String[] args) in /src/SegmentationFault/Program.cs:line 4
Aborted
#
```

#### ASP.NET App
`SegmentationFaultAspNet.csproj`
```
<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>
```

`Program.cs`
```csharp
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

throw new Exception("some exception");
```

`Dockerfile`
```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["SegmentationFaultAspNet/SegmentationFaultAspNet.csproj", "SegmentationFaultAspNet/"]
RUN dotnet restore "SegmentationFaultAspNet/SegmentationFaultAspNet.csproj"
COPY . .
WORKDIR "/src/SegmentationFaultAspNet"
RUN dotnet build "SegmentationFaultAspNet.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SegmentationFaultAspNet.csproj" -c Release -o /app/publish

#FROM mcr.microsoft.com/dotnet/aspnet:7.0
FROM mcr.microsoft.com/dotnet/aspnet:7.0-alpine
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT /bin/sh
```

##### Output with `mcr.microsoft.com/dotnet/aspnet:7.0-alpine`
```powershell
PS C:\docker> docker run --rm -it segmentation-fault-aspnet:alpine
/app # dotnet SegmentationFaultAspNet.dll
Segmentation fault
/app #
```

##### Output with `mcr.microsoft.com/dotnet/aspnet:7.0`
```powershell
PS C:\docker> docker run --rm -it segmentation-fault-aspnet:latest
# dotnet SegmentationFaultAspNet.dll
Unhandled exception. System.Exception: some exception
   at Program.<Main>$(String[] args) in /src/SegmentationFaultAspNet/Program.cs:line 4
Aborted
#
```

### Other Information
This behavior can be reproduced every time and there is no workaround as far as I'm concerned. A segmentation fault should not happen when using managed code.

### Output of `docker version`
Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:36:18 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.16.3 (96739)
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:26:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### Output of `docker info`
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.0)
  compose: Docker Compose (Docker Inc., v2.15.1)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.17)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 103
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.15.79.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 11.68GiB
 Name: docker-desktop
 ID: FU5I:QZGI:2VPC:IVED:MJT6:B6YF:G7MO:7MW2:PNIY:BF3T:JB6E:BQEX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support

**Comment by mthalman** [comment] 2023-02-28 14:17
Thanks for the detailed bug report @mario-zelger. This looks like a duplicate of https://github.com/dotnet/runtime/issues/81218. That fix didn't make it into the 7.0.3 (February) release but should be available in 7.0.4 (March).

cc @janvorli

**Closed by mthalman** 2023-02-28 14:17 UTC
Labels: bug, area-documentation, untriaged
