### ISSUE TITLE
Dotnet Restore SSL Error 

### ISSUE THREAD

**Issue by jbachand87** [dotnet/dotnet-docker#1341] opened 2019-09-25 19:09 UTC
## Steps to reproduce the issue
1. Create a docker file deriving from microsoft/dotnet:2.2-sdk
2. Create a sample C# application and copy it's source code into it
    ie: COPY ./src ./
3.Perform dotnet restore
     ie: RUN dotnet restore ./MyProject.sln

## Expected behavior
The dotnet restore should be able to call nuget successfully and download the nuget packages.

## Actual behavior
It fails on dotnet restore with this error:
/usr/share/dotnet/sdk/2.2.402/NuGet.targets(123,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [<solutionpath>]
/usr/share/dotnet/sdk/2.2.402/NuGet.targets(123,5): error :   The SSL connection could not be established, see inner exception. [<solutionpath>]
/usr/share/dotnet/sdk/2.2.402/NuGet.targets(123,5): error :   The remote certificate is invalid according to the validation procedure. [<solutionpath>]
The command '/bin/sh -c dotnet restore <solutionpath>' returned a non-zero code: 1

## Additional information (e.g. issue happens only occasionally)
This was happening, then it started working again. This morning, it started failing again. 

Additionally, I am able to get it to work on a different virtual machine running windows server.

## Output of `docker version`
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

## Output of `docker info`

Client:
 Debug Mode: false

Server:
 Containers: 73
  Running: 1
  Paused: 0
  Stopped: 72
 Images: 382
 Server Version: 19.03.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.934GiB
 Name: docker-desktop
 ID: CDDM:HWNM:XRNN:K5ZQ:6QWM:AVKA:7E5F:3AF2:4CHY:JQCU:XIUK:TS7A
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 28
  Goroutines: 43
  System Time: 2019-09-25T19:08:01.5727853Z
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by MichaelSimons** [comment] 2019-09-30 14:23
@jbachand87, I am not able to reproduce this issue.  Are you using any custom NuGet.config feeds?  Are you able to reproduce this every time?  Is this a Docker host specific issue?  Can you provide the exact steps you took to reproduce the problem?  Thanks

**Comment by vcsjones** [comment] 2019-09-30 15:40
@jbachand87 any chance you are on a corporate network that does TLS interception? If you run the following from your command line:

```shell
docker run -it mcr.microsoft.com/dotnet/core/sdk:2.2 openssl s_client -connect api.nuget.org:443
# Use Ctrl+D to exit
```

There should be a section called "Certificate chain" near the top, it should look something like this:

<pre>
Certificate chain
 0 s:/CN=*.nuget.org
   i:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT TLS CA 1
 1 s:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT TLS CA 1
   i:/C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root
---
</pre>

**Comment by jbachand87** [comment] 2019-10-03 14:12
I was able to resolve the issue by having my IT department put into place, a proxy bypass for my HOST OS’ IP address.

**Comment by MichaelSimons** [comment] 2019-10-03 14:32
Closing as this was a Docker host specific issue.

**Closed by MichaelSimons** 2019-10-03 14:32 UTC

**Comment by aron-truvian** [comment] 2020-01-15 22:05
I just ran into this issue, and it had nothing to do with TLS itself, but rather with the following Docker issue (which has been around for a loooong time with no fix):

[Wrong Date/Time](https://github.com/docker/for-win/issues/72)

What fixed it for me was restarting docker.

**Comment by epratik** [comment] 2021-03-19 10:05
Anyone facing this issue can try the following. This worked for me -
1. Create new solution - do not check enable docker support
2. Keep solution, project and the docker file in the same folder

**Comment by justinsantoro** [comment] 2022-01-20 22:35
> I just ran into this issue, and it had nothing to do with TLS itself, but rather with the following Docker issue (which has been around for a loooong time with no fix):
> 
> [Wrong Date/Time](https://github.com/docker/for-win/issues/72)
> 
> What fixed it for me was restarting docker.

I had the same issue. Restarting docker fixed it.
