### ISSUE TITLE
Docker failing to build ASP Net Core App because of missing references to System.IO.Pipelines

### ISSUE THREAD

**Issue by SirJosh3917** [dotnet/dotnet-docker#1744] opened 2020-03-15 15:10 UTC
## Steps to reproduce the issue
These are my exact steps, but I believe you may deviate from these steps.

A minimal repro attachment is provided here: 
[DockerTest123.zip](https://github.com/dotnet/dotnet-docker/files/4334632/DockerTest123.zip)

1. In Visual Studio 2019, create a new ASP.NET Core Web Application
2. Name "DockerTest123" (irrelevant)
3. Select "Empty", deselect "Configure for HTTPS", make sure "Enable Docker Support" is enabled with it set to "Linux"
4. Make sure "ASP.NET Core 3.1" is selected at the top, and ".NET Core" too
5. Click Create
6. Add the following line in Program.cs inbetween line 15 and 16 (this is just to use System.IO.Pipelines in the project somewhere) `PipeWriter pipeWriter = new Pipe().Writer;` (add the `using System.IO.Pipelines;` too)
6.5. The Dockerfile was put in the same folder as the csproj, so I had to move it out into the solution folder.
7. Build it in Visual Studio 2019, confirm it builds & runs (not under IISExpress or Docker, just use the DockerTest123 target).
8. Build it with Docker (running `docker build .` in the same folder where the Dockerfile is), confirm it doesn't build.

## Expected behavior

A docker container should be successfully built.

## Actual behavior

The project complains about missing references to System.IO.Pipelines

In the output provided, it says `Using cache`, but I do not believe this is an issue as I got the same output the first time.
```
Sending build context to Docker daemon  14.85kB
Step 1/16 : FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
 ---> e2cd20adb129
Step 2/16 : WORKDIR /app
 ---> Using cache
 ---> 8574abcf6d8f
Step 3/16 : EXPOSE 80
 ---> Using cache
 ---> b9f5e2c98037
Step 4/16 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
 ---> cfc38403c6bc
Step 5/16 : WORKDIR /src
 ---> Using cache
 ---> c77da0930caa
Step 6/16 : COPY ["DockerTest123/DockerTest123.csproj", "DockerTest123/"]
 ---> Using cache
 ---> dbb9b2001756
Step 7/16 : RUN dotnet restore "DockerTest123/DockerTest123.csproj"
 ---> Using cache
 ---> fdbe23bed69d
Step 8/16 : COPY . .
 ---> Using cache
 ---> ab58519409d0
Step 9/16 : WORKDIR "/src/DockerTest123"
 ---> Using cache
 ---> b2e6d5c3bb54
Step 10/16 : RUN dotnet build "DockerTest123.csproj" -c Release -o /app/build
 ---> Running in cb37c8e33bbf
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 34.55 ms for /src/DockerTest123/DockerTest123.csproj.
Program.cs(3,17): error CS0234: The type or namespace name 'Pipelines' does not exist in the namespace 'System.IO' (are you missing an assembly reference?) [/src/DockerTest123/DockerTest123.csproj]

Build FAILED.

Program.cs(3,17): error CS0234: The type or namespace name 'Pipelines' does not exist in the namespace 'System.IO' (are you missing an assembly reference?) [/src/DockerTest123/DockerTest123.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.18
The command '/bin/sh -c dotnet build "DockerTest123.csproj" -c Release -o /app/build' returned a non-zero code: 1
```

## Output of `docker version`

```
Client:
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.7
 Git commit:        74b1e89e8a
 Built:             Wed Jul 31 15:18:18 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Output of `docker info`

```
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 33
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.154-boot2docker
 Operating System: Boot2Docker 19.03.5 (TCL 10.1)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 989.5MiB
 Name: default
 ID: Y7YL:JR6T:FKU3:V46F:YDU4:XEYN:3WU3:SGMH:U3CQ:KJ4P:LWJE:XRFL
 Docker Root Dir: /mnt/sda1/var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
  provider=virtualbox
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by mthalman** [comment] 2020-03-19 12:53
Duplicate of https://github.com/dotnet/aspnetcore/issues/19133.

[Workaround](https://github.com/dotnet/aspnetcore/issues/19133#issuecomment-594179139) is to explicitly add a package reference to `System.IO.Pipelines`.

**Closed by mthalman** 2020-03-19 12:53 UTC
